### ISSUE TITLE
[BUG] Merging PSD glitches when a node has a Texture Offset

### ISSUE THREAD

**Issue by grillo-delmal** [Inochi2D/inochi-creator#100]
### Validations

- [X] I have checked for similar bug reports and could not find any.
- [X] I have tested and confirmed that this is an issue in an official branded build.

### Describe the bug

When importing the same PSD from where a model was created, the nodes that have a "Drawable > Texture Offset" value setted differently from 0 in their rig get their value sent to 0 and their mesh gets translated by the offset distance.

Checking the Re-translate option in the merge window doesn't make a difference for this issue.

Before importing
[base.webm](https://user-images.githubusercontent.com/11585030/194218999-6a88b1f7-3e7f-434d-a382-3613723bec35.webm)

After importing
[result.webm](https://user-images.githubusercontent.com/11585030/194219004-55343c25-286f-48e2-9041-f956a4799eec.webm)

### Reproduction

* Import a PSD
* Apply a Texture Offset to one of their nodes
* Merge the same PSD

### System Architecture

x86_64

### Operating System

Linux

### Version

commit+e7a44c2

### Additional Context

I was able to reproduce this on Linux and Windows

**Comment by LunaTheFoxgirl** [comment]
Fixed as of commit https://github.com/Inochi2D/inochi-creator/commit/c38191ffee2d3d481ec68b11441676d6e8e00c82
