### ISSUE TITLE
[BUG] Panel is disappeared forever on rare condition

### ISSUE THREAD

**Issue by seagetch** [Inochi2D/inochi-creator#101]
### Validations

- [X] I have checked for similar bug reports and could not find any.
- [X] I have tested and confirmed that this is an issue in an official branded build.

### Describe the bug

Main viewport has hidden tab.
When we drag panel to change layout, and drop over it to the location of hidden viewport tab, that panel becomes the member of that panel docking group, but hidden forever.
I had to remove ~/.config/.inochi-creator/imgui.ini to reset panel information.

### Reproduction

1. drag some panel.
2. move panel to the hidden tab area of viewport.
3. All of main viewport area is highlighted.
4. drop panel to the viewport.
5. dropped panel is hidden and cannot restore its visibility.

### System Architecture

x86_64

### Operating System

Linux

### Version

e7a44c2 remove harfbuzz .a as well from /usr/local/lib

**Comment by LunaTheFoxgirl** [comment]
Fixed as of https://github.com/Inochi2D/inochi-creator/commit/f33c0d3c71c9faad27f7eb5e61da60d059f58034
