### ISSUE TITLE
[BUG] Add / remove parameter cannot be restored in appropriate parameter group on undo

### ISSUE THREAD

**Issue by seagetch** [Inochi2D/inochi-creator#109]
### Validations

- [X] I have checked for similar bug reports and could not find any.
- [X] I have tested and confirmed that this is an issue in an official branded build.

### Describe the bug

If parameter belongs to some parameter group, and removed, it is not restored in original parameter group, but restored in top level when undo is executed.

### Reproduction

1. Add paramter to parameter group.
2. Remove parameter in the group.
3. Execute undo. parameter is restored at top level.

### System Architecture

x86_64

### Operating System

Linux

### Version

0.7.4

**Comment by LunaTheFoxgirl** [comment]
This fits in to the undo system retooling we'll need to do, so will probably get around to this at that time.

**Comment by seagetch** [comment]
Also noticed that "Duplicate" opertion for parameter cannot put duplicated one in the same group.
