### ISSUE TITLE
[Feature Request] Allow placing singular nodes snapped on to mesh editor mirror axes

### ISSUE THREAD

**Issue by HigasaMitsue** [Inochi2D/inochi-creator#115]
### Validations

- [X] I have checked for similar feature requests and could not find any.
- [X] I have made sure this is not an already-existing feature.

### Description

Currently the mesh editor mirror axes reflects all changes by mirroring vertex creation. However, placing a vertex which intersects an axis line does not snap to it, but instead creates two very closely places vertices, which would be undesirable in most cases.

### Suggested solution

When a vertex is placed very close (how close?) to an axis line, snap it to the axis line and only create one vertex. Snapping might be a toggleable feature.

### Alternative solution

When multiple vertices are placed very close together (how close?), replace them with one vertex averaging their positions. However, this alternate solution may impact other usage of the mesh editor and cedes a lot more user control, although again a toggle can be made for it.

**Comment by LunaTheFoxgirl** [comment]
Has been implemented a while ago
