### ISSUE TITLE
[Feature Request] Re-centering puppet origin

### ISSUE THREAD

**Issue by HigasaMitsue** [Inochi2D/inochi-creator#116]
### Validations

- [X] I have checked for similar feature requests and could not find any.
- [X] I have made sure this is not an already-existing feature.

### Description

When importing model art, sometimes the canvas is not centered quite right (mostly due to the original PSD). However, many models make use of symmetry, being able to control where the origin is is an important pre-requisite to any future mirroring features.

### Suggested solution

Allow the puppet origin to be moved around.
Ideally, have horizontal and vertical rulers extending from the origin so that alignment against symmetrical parts is easier.

### Alternative solution

Just have the user re-center in the PSD before import, although this kinda sucks if you've already imported into Creator and have done some work already, since you'd basically have to start over.

**Comment by LunaTheFoxgirl** [comment]
This can now be done with PSD merging
