### ISSUE TITLE
Maximizing does a fullscreen window instead of leaving room for the task bar.

### ISSUE THREAD

**Issue by playmer** [Inochi2D/inochi-creator#12]

**Comment by LunaTheFoxgirl** [comment]
This is a limit of SDL2 that is known, though maybe something can be done about it? 🤔

**Comment by playmer** [comment]
Hmm, from testing on a simple project I have (that is using a normal titlebar), `SDL_Maximize` does the correct thing. So something we're doing is causing this. Unsure if it's the custom titlebar though, have to do more testing.

**Comment by playmer** [comment]
Okay yeah it has to do with being borderless or not.

**Comment by playmer** [comment]
Hmm, so both the maximizing and aero snap (#10) issues are indeed down to the non-native title bar. Are we planning to do something special with it or did we want it out of cross platform consistency?  I noticed the imgui viewports also go nonnative, and making them native is still a little unclear to me. Plus they wouldn't be as smooth...

I dunno, stuff to think about. I think both of these could be hacked around, with this being easier than snap. But I figured I'd run the native window thing by you as they're fairly important features.

**Comment by LunaTheFoxgirl** [comment]
> 
> 
> Hmm, from testing on a simple project I have (that is using a normal titlebar), `SDL_Maximize` does the correct thing. So something we're doing is causing this. Unsure if it's the custom titlebar though, have to do more testing.

the problem is that our window is borderless to make space for the titlebar. Which causes maximize to go borderless fullscreen instead, I assume

**Comment by LunaTheFoxgirl** [comment]
Custom titlebar has been removed, this is no longer and issue.
