### ISSUE TITLE
[BUG] Drag and drop inx files into app doesn't work

### ISSUE THREAD

**Issue by grillo-delmal** [Inochi2D/inochi-creator#122]
### Validations

- [X] I have checked for similar bug reports and could not find any.
- [X] I have tested and confirmed that this is an issue in an official branded build.

### Describe the bug

When I try to drag and drop an INX file into the workspace I would expect for it to open the same way as it does when dragging the file into the app icon, but it doesn't work.

This happens on Windows and Linux, PSD files work as expected though.

### Reproduction

* Open inochi-creator
* Drag an inx file into the workspace
* ...
* ???
* profit

### System Architecture

x86_64

### Operating System

Linux

### Version

0.7.4.1

**Comment by r888800009** [comment]
This PR should support this feature
- https://github.com/Inochi2D/inochi-creator/pull/403
