### ISSUE TITLE
[BUG] Alt, Ctrl and Shift keys get locked/toggled on Linux

### ISSUE THREAD

**Issue by grillo-delmal** [Inochi2D/inochi-creator#123]
### Validations

- [X] I have checked for similar bug reports and could not find any.
- [X] I have tested and confirmed that this is an issue in an official branded build.

### Describe the bug

Whenever I press one of those keys, it gets locked until I press another one. What I mean by locked is that the application thinks that I'm holding the key while I'm actually not holding it.

I only was able to reproduce this on Linux, on windows it works as I would expect.

### Reproduction

* Open any model
* Press and release the CTRL hey
* Click on various items of the node tree
  * They should start selecting like if the key was pressed
* Press and release the ALT key or Shift key
* Click on various items of the node tree 
  * All the selected items should deselect, the only one selected would be the last one you picked

### System Architecture

x86_64

### Operating System

Linux

### Version

0.7.4.1

**Comment by LunaTheFoxgirl** [comment]
Which DE are you running again? Will try to see if I can reproduce.

**Comment by grillo-delmal** [comment]
Gnome on Fedora 36

**Comment by grillo-delmal** [comment]
This stopped being an issue a long time ago, most likely an SDL update fixed it
