### ISSUE TITLE
[Feature Request] Improve visibility of "copy mesh" action

### ISSUE THREAD

**Issue by grillo-delmal** [Inochi2D/inochi-creator#131]
### Validations

- [X] I have checked for similar feature requests and could not find any.
- [X] I have made sure this is not an already-existing feature.

### Description

Currently the copy mesh action feels more like a hidden trick than an actual feature. The current way to do it is to select a node you want to edit and then drag the node that has the mesh you want to copy into the "Edit Mesh" button.

### Suggested solution

Here are a couple of ideas to improve visibility.

1. When starting to drag a node element to drop to the "Edit Mesh" button, change the text of the "Edit Mesh" button to "Drop to apply mesh" or something like that.

2. Add a "mesh" section to the node inspector, since it's already a place where you have to drop deformation parameters to apply physics and to apply masks, it will be easier to understand that if you drag a node into it, it will copy the mesh.

**Comment by LunaTheFoxgirl** [comment]
Should be fixed with https://github.com/Inochi2D/inochi-creator/commit/2d0e4e2c5153292ea8bc250bd334441f53f6f2c4
