### ISSUE TITLE
[BUG] Mixing copying mesh and "Triangulate vertices" tool crashes the app.

### ISSUE THREAD

**Issue by grillo-delmal** [Inochi2D/inochi-creator#143]
### Validations

- [X] I have checked for similar bug reports and could not find any.
- [X] I have tested and confirmed that this is an issue in an official branded build.

### Describe the bug

If you copy a mesh from one part to another, and instead of applying the copy you try to activate the "Triangulate vertices" tool, the app crashes.

In the video bellow I detected the bug on a self compiled version, but I was able to reproduce it using the Aka model and the official 0.7.4.1 version (current)

App crash: https://www.youtube.com/watch?v=BuRpMKNd8Us&t=2350s

Retrying to reproduce: https://www.youtube.com/watch?v=BuRpMKNd8Us&t=3033s

As a user, you can avoid this crash simply by applying the copied mesh and then opening it again for edition.

### Reproduction

1. Open Aka.inx in inochi-creator
2. Select a part on the node tree (for instance the Skirt)
3. Drag some other part into the Edit Mesh button (for example, the Tail)
4. Press the "Triangulate vertices" button
5. ...
6. ???
7. Profit!

### System Architecture

x86_64

### Operating System

Windows

### Version

0.7.4.1

### Logs

=== Args State ===

=== Exception ===
core.exception.OutOfMemoryError@core\lifetime.d(126): Memory allocation failed
----------------
0x00007FF69B11DEBD in ImFontAtlas_SetTexID
0x00007FF69B11DC26 in ImFontAtlas_SetTexID
0x00007FF69B11ADEF in ImGuiInputTextState_GetSelectionStart
0x00007FF69B0FAB1A in ImGuiInputTextState_GetSelectionStart
0x00007FF69B0FBFF1 in ImGuiInputTextState_GetSelectionStart
0x00007FF69B102186 in ImGuiInputTextState_GetSelectionStart
0x00007FF69AFEDDF7 in igImAbs_Float
0x00007FF69AFED9C8 in igImAbs_Float
0x00007FF69AFEA51C in igImAbs_Float
0x00007FF69AFDF3D2
0x00007FF69AFDEF85
0x00007FF69AFF0C42 in igImAbs_Float
0x00007FF69B05848A in igImAbs_Float
0x00007FF69B0581A1 in igImAbs_Float
0x00007FF69B0FD804 in ImGuiInputTextState_GetSelectionStart
0x00007FF69B0FD490 in ImGuiInputTextState_GetSelectionStart
0x00007FF69B0FD764 in ImGuiInputTextState_GetSelectionStart
0x00007FF69B1BDAAC in ImGui_ImplOpenGL3_Shutdown
0x00007FF8A7CA7034 in BaseThreadInitThunk
0x00007FF8A8BA26A1 in RtlUserThreadStart

**Comment by LunaTheFoxgirl** [comment]
Fixed by #176
