### ISSUE TITLE
[Feature Request] Add save reminder when closing the app.

### ISSUE THREAD

**Issue by helloar14** [Inochi2D/inochi-creator#145]
### Validations

- [X] I have checked for similar feature requests and could not find any.
- [X] I have made sure this is not an already-existing feature.

### Description

When closing Creator, there is no reminder/question to save the current file before closing. Adding this feature will help forgetful people like me very much!

### Suggested solution

Add a confirmation before Creator is closed, asking whether the user want to save the file first or not. The detection can be taken from History panel, for example (if this panel is not empty, then we assume that the file has been modified and then asks for saving before closing).

**Comment by Richardn2002** [comment]
Is this still blocked by `libsoba`? Multiple Bilibili users are also requesting this.
