### ISSUE TITLE
[Feature Request] Add support for Shift-Click in Tree View.

### ISSUE THREAD

**Issue by cid-chan** [Inochi2D/inochi-creator#156]
### Validations

- [X] I have checked for similar feature requests and could not find any.
- [X] I have made sure this is not an already-existing feature.

### Description

I opened Inochi2D for the first time today.

I used "Image Folder" import to dump a bunch of image files into an empty project.
I wanted to Move All Files into a Composite I called "Unsorted".
I want to select a range of objects within the tree view. 

### Suggested solution

Other applications like File-Explorers usually deal with this using Shift+Click.

1. Select one entry normally.
2. Select a second entry while holding Shift.

This results in all items between the first and the second one (both including) to be selected.

**Comment by LunaTheFoxgirl** [comment]
Shift in general means select from start to end, to multi-select individual items hold ctrl.
I've not found a good way to do range select yet over the tree but I may look in to this sooner rather than later
