### ISSUE TITLE
[BUG] Cursor offset when trying to edit mesh to armed parameter

### ISSUE THREAD

**Issue by Kiy-Ko** [Inochi2D/inochi-creator#164]
### Validations

- [X] I have checked for similar bug reports and could not find any.
- [X] I have tested and confirmed that this is an issue in an official branded build.

### Describe the bug

When editing a mesh during an armed parameter, the software thinks the cursor is in a different place than it actually is.

https://user-images.githubusercontent.com/57007114/213307036-eec3e5e4-02d6-4b93-9227-055448775afa.mp4

I'm working in usual 1080p.

### Reproduction

1. Arm parameter
2. Try to move vertices of a mesh, drag cursor to see there is an offset

### System Architecture

x86_64

### Operating System

Windows

### Version

78bebcf

**Comment by playmer** [comment]
What's you scale set to on your monitor?

**Comment by Kiy-Ko** [comment]
100% (Recommended)

**Comment by playmer** [comment]
Sounds like this got fixed by #165?

**Comment by seagetch** [comment]
It seems fixed.
