### ISSUE TITLE
[BUG] Dragging vertex no longer deforms texture

### ISSUE THREAD

**Issue by HoneyBuzzBee** [Inochi2D/inochi-creator#171]
### Validations

- [X] I have checked for similar bug reports and could not find any.
- [X] I have tested and confirmed that this is an issue in an official branded build.

### Describe the bug

I just built from the latest commit to test out the new model I made in creator, but when I armed a parameter and tried to move around the mesh I found out that moving around the vertices doesn't affect the texture, which remains unchanged. On further experimentation I noticed that the path deform tool does properly deform the texture. Furthermore, when I move the vertices with the vertex tool, draw a path and hit TAB to go into the path edit mode the texture does deform with the vertices. 
[Screencast from 2023-02-11 02-50-23.webm](https://user-images.githubusercontent.com/121172411/218232467-8b9e4cc6-b6ca-4b97-9bca-7f497dcb1cf0.webm)

### Reproduction

1. Create a parameter
2. Arm parameter
3. Edit mesh with vertex tool

### System Architecture

x86_64

### Operating System

Linux

### Version

9e28c3cfaaaecab94fbf39c868a5726600f8cc90

**Comment by LunaTheFoxgirl** [comment]
Fixed by #172
