### ISSUE TITLE
[BUG] Using the 'Copy Mesh' function does not copy the mesh 

### ISSUE THREAD

**Issue by HoneyBuzzBee** [Inochi2D/inochi-creator#174]
### Validations

- [X] I have checked for similar bug reports and could not find any.
- [X] I have tested and confirmed that this is an issue in an official branded build.

### Describe the bug

In my model I have numerous textures that are copies or mirrors of each other and as such I want to copy the meshes between them to save the time and hassle of meshing each of these objects manually. However when I try to use the mesh copying functionality using the instructions described in the Inochi2D Unofficial Documentation:
**_In order to copy meshes, make sure you are not Arming a parameter.
In the Nodes panel, select the target Part you want to copy the mesh to, and drag the source Part you want to copy from to the Edit Mesh button on the bottom left of the model viewport._**
the mesh doesn't get copied over. I've tried this with various objects and various meshes with identical results. 

### Reproduction

1. Select an object
2. Drag object with desired mesh from nodes menu onto the 'Copy Mesh' button

### System Architecture

x86_64

### Operating System

Linux

### Version

e2460d14de05f331307caa2369a7f70e1aeae7aa

### Additional Context

[Screencast from 2023-02-11 22-28-33.webm](https://user-images.githubusercontent.com/121172411/218282426-6c9041f9-ee2a-403c-bbdc-9ee7854acff2.webm)

**Comment by LunaTheFoxgirl** [comment]
Fixed by #175
