### ISSUE TITLE
[BUG] Dragging a vertex while editing multiple meshes draws selection box on cursor

### ISSUE THREAD

**Issue by HoneyBuzzBee** [Inochi2D/inochi-creator#177]
### Validations

- [X] I have checked for similar bug reports and could not find any.
- [X] I have tested and confirmed that this is an issue in an official branded build.

### Describe the bug

It's a pretty minor bug  but I'll mention it anyway. When you're arming a parameter with multiple meshes selected and you drag a vertex around with the vertex tool, a selection box gets drawn at the cursor. This does not happen with a single mesh selected. 

### Reproduction

1. Select multiple meshes
2. Arm a parameter
3. Drag a vertex around with the vertex tool

### System Architecture

x86_64

### Operating System

Linux

### Version

24c7cfb04b1cda17079e235fde8b252b86f33256

### Additional Context

[Screencast from 2023-02-13 01-19-05.webm](https://user-images.githubusercontent.com/121172411/218346760-da58797c-71ec-4eb7-9102-71161505e83b.webm)

**Comment by LunaTheFoxgirl** [comment]
Fixed by #182.
