### ISSUE TITLE
[BUG] Can't manipulate multiple meshes simultaneously with vertex tool

### ISSUE THREAD

**Issue by HoneyBuzzBee** [Inochi2D/inochi-creator#178]
### Validations

- [X] I have checked for similar bug reports and could not find any.
- [X] I have tested and confirmed that this is an issue in an official branded build.

### Describe the bug

When I arm a parameter with multiple meshes selected, select (a number of) vertices from **both** meshes and try to drag them around with the vertex tool, only the vertices of the mesh that has the cursor over it get moved while the vertices of the other mesh don't move at all. A binding gets created for both the mesh that moves **and** the mesh that doesn't move. When hitting ctrl+z to undo the change the binding for the mesh that did move gets removed while the binding for the mesh that didn't move stays in the list. 
Manipulating multiple meshes with the path tool does work as intended. 

Edit: This behaviour doesn't happen when moving the vertices with the keyboard. 

### Reproduction

1. Select multiple meshes
2. Arm a parameter
3. Select vertices for multiple meshes
4. Drag vertices around with vertex tool

### System Architecture

x86_64

### Operating System

Linux

### Version

24c7cfb04b1cda17079e235fde8b252b86f33256

### Additional Context

[Screencast from 2023-02-13 01-21-01.webm](https://user-images.githubusercontent.com/121172411/218347517-2ce19fc1-cd39-4591-ab0e-04d67add041a.webm)

**Comment by LunaTheFoxgirl** [comment]
Fixed by #182.
