### ISSUE TITLE
[BUG] Switching tools after triangulating mesh undoes changes

### ISSUE THREAD

**Issue by HoneyBuzzBee** [Inochi2D/inochi-creator#179]
### Validations

- [X] I have checked for similar bug reports and could not find any.
- [X] I have tested and confirmed that this is an issue in an official branded build.

### Describe the bug

When you edit a mesh and use the triangulate vertex tool, the mesh gets triangulated as intended. However when you then switch to the edge tool or the path deform tool, the changes that triangulate made get undone. Also, when you have a tool other than the vertex tool selected and you press the triangulate vertices button, nothing happens. 

### Reproduction

1. Select object with mesh
2. Click 'edit mesh'
3. Click 'Triangulate vertices'
4. Switch to another tool

### System Architecture

x86_64

### Operating System

Linux

### Version

24c7cfb04b1cda17079e235fde8b252b86f33256

### Additional Context

[Screencast from 2023-02-11 22-26-58.webm](https://user-images.githubusercontent.com/121172411/218348536-182297c1-6b8c-488e-9f64-3559e84aa1c3.webm)

**Comment by seagetch** [comment]
In the current specification, you need to select drop down of auto triangulate tool, and then need to push "Bake" to apply the result of auto triangulation.

**Comment by seagetch** [comment]
We can close this issue.
