### ISSUE TITLE
[BUG] In Edit Mesh, Mirror Vertical doesn't work

### ISSUE THREAD

**Issue by HoneyBuzzBee** [Inochi2D/inochi-creator#180]
### Validations

- [X] I have checked for similar bug reports and could not find any.
- [X] I have tested and confirmed that this is an issue in an official branded build.

### Describe the bug

When you're drawing a mesh in 'Edit Mesh' and enable the horizontal mirror, vertices placed get mirrored as intended. However when you enable the vertical mirror the vertices don't get mirrored vertically. Instead, it behaves exactly the same as the horizontal mirror **except** when you select both the horizontal and vertical mirror at the same time and then deselect the horizontal mirror. When you do that, no vertices get mirrored. 

### Reproduction

1. Select object with mesh
2. Click 'Edit Mesh'
3. Click 'Mirror Vertically'
4. Place a vertex

### System Architecture

x86_64

### Operating System

Linux

### Version

24c7cfb04b1cda17079e235fde8b252b86f33256

### Additional Context

[Screencast from 2023-02-13 02-00-12.webm](https://user-images.githubusercontent.com/121172411/218349567-c1a92be2-8585-4b8e-96ba-df26a67a74d6.webm)

**Comment by LunaTheFoxgirl** [comment]
Fixed by #182.
