### ISSUE TITLE
[BUG] Crash at launch

### ISSUE THREAD

**Issue by zeRyoga** [Inochi2D/inochi-creator#183]
### Validations

- [X] I have checked for similar bug reports and could not find any.
- [X] I have tested and confirmed that this is an issue in an official branded build.

### Describe the bug

I'm trying to launch Inochi creator 7.4.1 on windows, but I get an Inochi Creator Crashdump:

Here the content:

=== Args State ===

=== Exception ===
Invalid UTF sequence: a9x - Invalid UTF-8 sequence (at index 1)

### Reproduction

1. Install Inochi Creator on windows.
2. dbl click on inochi-creator.exe
3. Getting crashdump

### System Architecture

x86_64

### Operating System

Windows

### Version

7.4.1

### Logs

=== Args State ===

=== Exception ===
Invalid UTF sequence: a9x - Invalid UTF-8 sequence (at index 1)

**Comment by LunaTheFoxgirl** [comment]
I'm afraid there's not enough information here for me to reproduce the issue, have you tried deleting settings.json in %AppData%/.inochi-creator?

**Comment by zeRyoga** [comment]
Thank you I was so desperate :), it's working now

**Comment by zeRyoga** [comment]
Thank you Luna, you're software is great.
