### ISSUE TITLE
[BUG] Undoing after merging image file crashes the program

### ISSUE THREAD

**Issue by HoneyBuzzBee** [Inochi2D/inochi-creator#184]
### Validations

- [X] I have checked for similar bug reports and could not find any.
- [X] I have tested and confirmed that this is an issue in an official branded build.

### Describe the bug

I was working on my rig and needed to import a PNG into my project, which all worked fine. After a bit of work I needed to undo some changes so I hit ctrl+z a few times, which crashed the program to crash. After messing around with it a bit I found out that if you undo right after you merged an image file the crash occurs. This doesn't happen when you import a PSD. 
When the crash happens, the following gets output in the terminal:
```
core.exception.RangeError@source/creator/actions/node.d(96): Range violation
----------------
??:? _d_arrayboundsp [0x5566e586004d]
source/creator/actions/node.d:96 void creator.actions.node.NodeMoveAction.rollback() [0x5566e550637c]
source/creator/core/actionstack.d:63 void creator.core.actionstack.incActionUndo() [0x5566e55ce8da]
source/creator/core/package.d:799 void creator.core.incHandleShortcuts() [0x5566e55d8a18]
source/app.d:118 void app.incUpdate() [0x5566e54ff934]
source/app.d:91 _Dmain [0x5566e54ff8c0]
```

### Reproduction

1. Open an INX
2. Go to file>merge>Image Files
3. Select an image file
4. Hit undo

### System Architecture

x86_64

### Operating System

Linux

### Version

24c7cfb04b1cda17079e235fde8b252b86f33256

**Comment by seagetch** [comment]
Maybe most reliable workaround for this is to clear history buffer after merged images.

**Comment by LunaTheFoxgirl** [comment]
Fixed by https://github.com/Inochi2D/inochi-creator/commit/31c111ef3e747f996c2ae3cf17e835ae18e04f07
