### ISSUE TITLE
[BUG] In Edit Mesh, selection box doesn't get undrawn after releasing click and vertices 'stick' to cursor

### ISSUE THREAD

**Issue by HoneyBuzzBee** [Inochi2D/inochi-creator#186]
### Validations

- [X] I have checked for similar bug reports and could not find any.
- [X] I have tested and confirmed that this is an issue in an official branded build.

### Describe the bug
Since #182  whenever you go and draw a selection box the box stays drawn even after you release the mouse button. Clicking the mouse again just draws another box. 

Edit: Also when you drag a vertex it 'sticks' to the cursor.
### Reproduction

1. Select object with mesh
2. Click 'Edit Mesh'
3. Draw a selection box

### System Architecture

x86_64

### Operating System

Linux

### Version

a0241e38e3f5fadcf417952b2d62ea87589ac624

### Additional Context

[Screencast from 2023-02-14 15-56-27.webm](https://user-images.githubusercontent.com/121172411/218776224-6c968b80-0c9b-4822-bcdc-653a0fbb5380.webm)

**Comment by LunaTheFoxgirl** [comment]
Fixed by #187.
