### ISSUE TITLE
[BUG] Path nodes rotate with x, y rotation of object

### ISSUE THREAD

**Issue by HoneyBuzzBee** [Inochi2D/inochi-creator#188]
### Validations

- [X] I have checked for similar bug reports and could not find any.
- [X] I have tested and confirmed that this is an issue in an official branded build.

### Describe the bug

I just noticed that paths inherit the x and y rotation of the mesh, meaning that when you draw a path and rotate the mesh the path rotates with it, or when you draw a path on a rotated mesh the nodes get drawn with a rotational offset. While the nodes are visually offset, it seems that the actual coordinates of the nodes remain unchanged, so you won't know where to click to select them. It would be preferable if the actual location of the path nodes matches its visual location, right now it is almost impossible to use this tool on a mesh with x or y rotation. (Not that you typically would, but still...)

### Reproduction

1. Select a meshed object
2. Arm a parameter
3. Rotate mesh on x and/or y axis
4. Draw a path

### System Architecture

x86_64

### Operating System

Linux

### Version

e8bd3241887b72d7182e7973fcf7bd5a6d14513f

### Additional Context

[out.webm](https://user-images.githubusercontent.com/121172411/218863350-8630fdcd-83a5-400e-b664-2ff126d4e91e.webm)

**Comment by seagetch** [comment]
This is not limited to the path nodes, same for other tool.
And this seems a bug which exist from previous release.

I guess this is the problem of transformation of mouse cursor position from screen coordinate to the local coordinate.

**Comment by seagetch** [comment]
We assume that cursor is on flat screen, and position is assumed (x, y, 0).
But rotation of X and Y breaks this assumption. maybe that is the reason to cause this problem.
(Translation along with Z-axis also breaks the assumption, but (x, y, 0) and (x, y, z) gives same result ofter translation, so this doesn't cause any problem in that case.)

I have no idea how to solve this problem yet.

**Comment by r888800009** [comment]
PR https://github.com/Inochi2D/inochi-creator/pull/410 should resolve the issue.
