### ISSUE TITLE
[BUG] Undoing moving vertices in a mesh doesn't move the red dots back

### ISSUE THREAD

**Issue by ShatReal** [Inochi2D/inochi-creator#200]
### Validations

- [X] I have checked for similar bug reports and could not find any.
- [X] I have tested and confirmed that this is an issue in an official branded build.

### Describe the bug

I moved some vertices and undid it but the red dots didn't move back.

### Reproduction

Move some vertices and then undo it.

### System Architecture

None

### Operating System

Windows

### Version

commit+757eb65

### Additional Context

![image](https://user-images.githubusercontent.com/69117768/222939392-b105bbd8-ba17-4901-b57b-5082bf790689.png)

**Comment by seagetch** [comment]
This may be fixed by https://github.com/Inochi2D/inochi-creator/pull/218

**Comment by LunaTheFoxgirl** [comment]
Confirmed fixed by #218
