### ISSUE TITLE
[Feature Request] Add a toggle for viewport background color change

### ISSUE THREAD

**Issue by helloar14** [Inochi2D/inochi-creator#207]
### Validations

- [X] I have checked for similar feature requests and could not find any.
- [X] I have made sure this is not an already-existing feature.

### Description

Currently the viewport follows app's current theme (light or dark). It will be very useful if there is a switch between light/dark viewport background in the toolbar.

### Suggested solution

Add a toggle between dark/light viewport color in the toolbar.

### Alternative solution

- Alternatively, add toggle between dark/light UI theme in the toolbar (might be easier/faster since the functionality is already available, just placed in a rather inconvenient place).
- In the future, it might be even more useful if we can switch between solid and checkerboard background pattern.

**Comment by LunaTheFoxgirl** [comment]
Fixed as of https://github.com/Inochi2D/inochi-creator/commit/5bc52e59f116c47dc364e50d598b0c32e1c0e06d
