### ISSUE TITLE
[Feature Request] Reset All Parameters Button

### ISSUE THREAD

**Issue by helloar14** [Inochi2D/inochi-creator#229]
### Validations

- [X] I have checked for similar feature requests and could not find any.
- [X] I have made sure this is not an already-existing feature.

### Description

As far as I know, there is a button to reset all physics, but not reset all parameters regardless of type (physics or not). I think this can be a very useful utility.

### Suggested solution

Add a button to reset all parameters to its default value.

**Comment by LunaTheFoxgirl** [comment]
Implemented as of https://github.com/Inochi2D/inochi-creator/commit/e4bb4886063439ef5a87f41fdb49f9cc1fce2cb5
