### ISSUE TITLE
[BUG] 2D Parameter Value Shifts When Adding Keyframes

### ISSUE THREAD

**Issue by helloar14** [Inochi2D/inochi-creator#230]
### Validations

- [X] I have checked for similar bug reports and could not find any.
- [X] I have tested and confirmed that this is an issue in an official branded build.

### Describe the bug

Adding new keyframe for 2D parameters somehow causes the value to shift. This does not happen with 1D parameters, only 2D.

### Reproduction

1. Go to Edit Animation mode.
2. Add a new keyframe for 2D parameter.
3. Value immediately shifts (for -1 to 1 parameters usually it will go x=1, y=1)

https://user-images.githubusercontent.com/7506276/231296294-689507ad-ca59-4da1-9d2e-56748eed9a63.mp4

### System Architecture

x86_64

### Operating System

Windows

### Version

5bc52e5

**Comment by LunaTheFoxgirl** [comment]
Fixed by https://github.com/Inochi2D/inochi2d/commit/32c63d3540a5b3d81f4f2c65844dd8046cd58330
