### ISSUE TITLE
[BUG] Undo history of vertex edit in "Edit Mesh" mode must be altered by single "ParameterBindingAllValueChangeAction" when changes are applied to Drawable.

### ISSUE THREAD

**Issue by seagetch** [Inochi2D/inochi-creator#233]
### Validations

- [X] I have checked for similar bug reports and could not find any.
- [X] I have tested and confirmed that this is an issue in an official branded build.

### Describe the bug

After editing vertices of mesh using "Edit Mesh" mode, and press "Apply", all change can be rolled back by single "ParameterBindingAllValueChangeAction."
But history of edit in "Edit Mesh" mode is still on the undo history, and do nothing meaningful on undo/redo action.
All of the edit history in "Edit Mesh" must be replaced by single "ParameterBindingAllValueChangeAction"

### Reproduction

1. Go to "Edit Mesh" mode.
2.  Edit vertices by several step.
3.  Press "Apply" button to apply change.
4. Undo one step. (applied change by "Edit Mesh" is rolled back.)
5. Undo furthermore. (Undo action in "Edit Mesh" mode is executed on History panel, but no effect.)

### System Architecture

None

### Operating System

None

### Version

latest commit (bc05cfa)

**Comment by LunaTheFoxgirl** [comment]
That's quite a title

**Comment by seagetch** [comment]
Does actionIndex actually used in actionstack.d?
