### ISSUE TITLE
[BUG] Creating a new parameter group causes a crash

### ISSUE THREAD

**Issue by LunaTheFoxgirl** [Inochi2D/inochi-creator#234]
### Validations

- [X] I have checked for similar bug reports and could not find any.
- [X] I have tested and confirmed that this is an issue in an official branded build.

### Describe the bug

Creating a new parameter group causes a crash immediately, it's a segmentation fault so probably some null pointer being dereferenced.

### Reproduction

1. Create project
2. Create 2 parameters
3. Drag one to the other
4. explosion

### System Architecture

None

### Operating System

None

**Comment by seagetch** [comment]
This happens at `source/creator/panels/parameters.d:791`
```
    void moveParameter(Parameter from, ExParameterGroup to = null, int index = 0) {
        (cast(ExParameter)from).setParent(to);
    }
```
I assumed all model are made by ExPuppet and ExParameter, but somtimes it isn't...

**Comment by seagetch** [comment]
My recent patch for new parameter format assumes that all parameters and puppet are instances of ExParameter and ExPuppet, and without that, parameter group cannot be constructed.
I suggest to use ExPuppet and ExParameter for all cases in creator, including import INP / PSD, and new project creation.

**Comment by LunaTheFoxgirl** [comment]
Fixed by https://github.com/Inochi2D/inochi-creator/commit/995ada8f7b1955357f8117dfb7ecee100d74a527
