### ISSUE TITLE
[BUG] Bug in Animation timeline where scrubbing sometimes doesn't update

### ISSUE THREAD

**Issue by ExpiredPopsicle** [Inochi2D/inochi-creator#239]
### Validations

- [X] I have checked for similar bug reports and could not find any.
- [X] I have tested and confirmed that this is an issue in an official branded build.

### Describe the bug

Scrubbing in the timeline does not actually update the view sometimes.

Additionally, ending scrubbing resets state.

### Reproduction

See description.

### System Architecture

None

### Operating System

None

**Comment by LunaTheFoxgirl** [comment]
Fixed by https://github.com/Inochi2D/inochi-creator/commit/5ea554be5a7cb3860134fd1ec689365717babc60
