### ISSUE TITLE
Feature Suggestion: Set Texture Tint in KeyPoints

### ISSUE THREAD

**Issue by lualucky** [Inochi2D/inochi-creator#24]
I would like the ability to animate the tint of a texture in keypoints.
Ideally the tint keypoints could be on a node and then be applied to all children textures of the node.

Even better would be to apply the tint with different blend modes. I believe a normal tint is applied with the texture as multiply, but screen would be fantastic as well.

**Comment by LunaTheFoxgirl** [comment]
This feature has been implemented
