### ISSUE TITLE
[BUG] Bug in Animation Timeline where Forced mode is not the default

### ISSUE THREAD

**Issue by ExpiredPopsicle** [Inochi2D/inochi-creator#240]
### Validations

- [X] I have checked for similar bug reports and could not find any.
- [X] I have tested and confirmed that this is an issue in an official branded build.

### Describe the bug

Animation timeline lanes are, by default, additive only. They should be forced mode instead.

### Reproduction

See description.

### System Architecture

None

### Operating System

None

**Comment by LunaTheFoxgirl** [comment]
Fixed by https://github.com/Inochi2D/inochi2d/commit/32c63d3540a5b3d81f4f2c65844dd8046cd58330
