### ISSUE TITLE
[Feature Request] Sort out flatpak builds

### ISSUE THREAD

**Issue by LunaTheFoxgirl** [Inochi2D/inochi-creator#241]
### Validations

- [X] I have checked for similar feature requests and could not find any.
- [X] I have made sure this is not an already-existing feature.

### Description

We need to get nightly, release candidate and arm64 flatpaks sorted before we release 0.8, will need @orowith2os's help with this.

### Suggested solution

See above.

**Comment by orowith2os** [comment]
Flatpak bundles shouldn't be too hard to get going, the manifest would just need to be submitted here (and to Session) with the appropriate workflow.

Are you fine with holding off on any new stable release until I'm able to get on this? RCs excluded. I estimate a few weeks, I've got a bunch of essays I need to work on.

**Comment by LunaTheFoxgirl** [comment]
Not really, the plan is to release this ASAP. (this week or next week)

People have been waiting long enough for this =w=

**Comment by LunaTheFoxgirl** [comment]
This is more or less solved now minus nightlies
