### ISSUE TITLE
[BUG] Autosave history show files which does not exist.

### ISSUE THREAD

**Issue by seagetch** [Inochi2D/inochi-creator#245]
### Validations

- [X] I have checked for similar bug reports and could not find any.
- [X] I have tested and confirmed that this is an issue in an official branded build.

### Describe the bug

"File > Recent" menu has a "Autosaves" sub menu, and shows history of auto-saved files.
It lists files which is already deleted because it exceeds the maximum limit of auto-save, and kicked out.
![image](https://user-images.githubusercontent.com/449741/234370333-78c7de35-ba8e-4c73-9c39-9854f6b56f8c.png)

### Reproduction

1. Open some model.
2. Leave it for some time (1 hour or so.)
3. Chose menu "File > Recent > Autosaves"
4. Click oldest file, and failed to open it (error dialog is shown with "No such file" message)

### System Architecture

x86_64

### Operating System

Linux

### Version

0.8 RC1

**Comment by LunaTheFoxgirl** [comment]
Fixed by https://github.com/Inochi2D/inochi-creator/commit/1cc08a512cf91e844798b3260dacc91335788aea
