### ISSUE TITLE
[BUG] Last loop of video export does not animate

### ISSUE THREAD

**Issue by 20kdc** [Inochi2D/inochi-creator#246]
### Validations

- [X] I have checked for similar bug reports and could not find any.
- [X] I have tested and confirmed that this is an issue in an official branded build.

### Describe the bug

When the amount of loops in a video export is above zero, the last loop is not animated.

### Reproduction

Project for reproducing the issue:
[Measurement.inx.zip](https://github.com/Inochi2D/inochi-creator/files/11327129/Measurement.inx.zip)

Steps:
1. Load project
2. File->Export->Video
3. Save as MP4
4. Set loops to any value above 0, leave other settings alone. A good amount of loops for this is 2 or 3.
5. Review output video: The last loop does not animate

### System Architecture

x86\_64

### Operating System

Ubuntu 22.04.2 LTS (Jammy Jellyfish)

### Version

v0.8.0-rc1

### Additional Context

https://user-images.githubusercontent.com/22304167/234412761-7f4fb859-267e-49c8-8659-002937139105.mp4

**Comment by LunaTheFoxgirl** [comment]
Fixed by https://github.com/Inochi2D/inochi-creator/commit/9230f65b889a8ecc75047f8038236b4ecd45722d

**Comment by LunaTheFoxgirl** [comment]
https://user-images.githubusercontent.com/7032834/234417662-4fd185e9-8db5-47fe-8b32-41b5f2f4cff9.mp4
Exported video of 3 loops with the commit applied
