### ISSUE TITLE
[BUG] App crashes in Animation mode when changing Framerate

### ISSUE THREAD

**Issue by grillo-delmal** [Inochi2D/inochi-creator#250]
### Validations

- [X] I have checked for similar bug reports and could not find any.
- [X] I have tested and confirmed that this is an issue in an official branded build.

### Describe the bug

When picking a custom framerate for an animation and then trying to use the combo box to pick another one, the app crashes.

This seems to be caused by ID conflicts between elements in IMGUI, this could be fixed by changing the imgui ID of one of the Framerate elements in that panel, either by changing the name of one of them or by enclosing one of them in `igPushID` and `igPopID` calls

### Reproduction

* Open a puppet
* Click the "Edit Animation" button
* Create a new animation or edit an existing one in the Animation List
* Pick "Custom Framerate" in the "Framerate" Combobox
* Try to pick any other Framerate in the combobox (you shouldn't be able to)
* Click the Framerate selector
* Try to pick any other Framerate in the combobox (crash)

### System Architecture

x86_64

### Operating System

Linux

### Version

v8.0.0-rc1; 24b878bc

### Logs

```cpp
#0  __pthread_kill_implementation (threadid=<optimized out>, signo=signo@entry=6, no_tid=no_tid@entry=0) at pthread_kill.c:44
#1  0x00007ffff71cec03 in __pthread_kill_internal (signo=6, threadid=<optimized out>) at pthread_kill.c:78
#2  0x00007ffff717daee in __GI_raise (sig=sig@entry=6) at ../sysdeps/posix/raise.c:26
#3  0x00007ffff716687f in __GI_abort () at abort.c:79
#4  0x00007ffff716679b in __assert_fail_base
    (fmt=0x7ffff72e3a98 "%s%s%s:%u: %s%sAssertion `%s' failed.\n%n", assertion=assertion@entry=0x1b8d1b8 "mouse_button >= 0 && mouse_button < ImGuiMouseButton_COUNT", file=file@entry=0x1b8d178 "/opt/src/bindbc-imgui/deps/cimgui/imgui/imgui_widgets.cpp", line=line@entry=636, function=function@entry=0x1b8d120 "bool ImGui::ButtonBehavior(const ImRect&, ImGuiID, bool*, bool*, ImGuiButtonFlags)") at assert.c:92
#5  0x00007ffff7176177 in __assert_fail
    (assertion=0x1b8d1b8 "mouse_button >= 0 && mouse_button < ImGuiMouseButton_COUNT", file=0x1b8d178 "/opt/src/bindbc-imgui/deps/cimgui/imgui/imgui_widgets.cpp", line=636, function=0x1b8d120 "bool ImGui::ButtonBehavior(const ImRect&, ImGuiID, bool*, bool*, ImGuiButtonFlags)") at assert.c:101
#6  0x000000000068abe1 in ImGui::ButtonBehavior(ImRect const&, unsigned int, bool*, bool*, int) ()
#7  0x000000000068f739 in ImGui::BeginCombo(char const*, char const*, int) ()
#8  0x00000000005d7554 in igBeginCombo ()
#9  0x000000000046a3f2 in _D7creator7windows8editanim19EditAnimationWindow8onUpdateMFZv (this=0x7ffff6bb7100) at source/creator/windows/editanim.d:100
#10 0x0000000000461e22 in _D7creator7windows6Window6updateMFZv (this=0x7ffff6bb7100) at source/creator/windows/package.d:112
#11 0x000000000046250f in _D7creator7windows16incUpdateWindowsFZv () at source/creator/windows/package.d:237
#12 0x00000000005d5461 in _D3app9incUpdateFZv () at source/app.d:136
#13 0x00000000005d53bf in _Dmain (args=...) at source/app.d:97
```

**Comment by LunaTheFoxgirl** [comment]
Fixed by https://github.com/Inochi2D/inochi-creator/commit/f9d56ef23a81f168f12587a8090f05a72e5ed080
