### ISSUE TITLE
[BUG] Layers are imported twice for children of LayerGroup.

### ISSUE THREAD

**Issue by seagetch** [Inochi2D/inochi-creator#251]
### Validations

- [X] I have checked for similar bug reports and could not find any.
- [X] I have tested and confirmed that this is an issue in an official branded build.

### Describe the bug

When imported PSD which has LayerGroup, children of LayerGroup are imported twice.

### Reproduction

1. Prepare PSD which has LayerGroup.
2. Select "Import > Photoshop Document"
3. Select Above file.

### System Architecture

x86_64

### Operating System

Linux

### Version

0.8 RC2

**Comment by LunaTheFoxgirl** [comment]
Fixed by https://github.com/Inochi2D/inochi-creator/commit/e413b6e0314711d64488bc91d9a67439299a127e
