### ISSUE TITLE
[BUG] Rendering issues on Intel GPUs

### ISSUE THREAD

**Issue by penbuvt** [Inochi2D/inochi-creator#261]
### Validations

- [X] I have checked for similar bug reports and could not find any.
- [X] I have tested and confirmed that this is an issue in an official branded build.

### Describe the bug

As described in [Discord](https://discord.com/channels/855173611409506334/888154799357440030/1102878753010499654):

> Both Creator and Session are not rendering the eyes of the model correctly, whereas Creator 0.7.4.1 and Session 0.5.4 render it as expected. In Creator, the iris of the right eye (screen left side; labelled in the model as "pupil") seems to be rendered incorrectly behind the white of the eye. In Session, the same behaviour is exhibited, but when hooked up to VTube Studio (Android) tracking, it's rendered correctly in some angles but not others. Attempting to relayer the iris so that it appears correct in Creator causes the irises to appear above the eyelids in Session. Furthermore, attempting to hide and show the right iris causes the left one to disappear.

The current hypothesis is that this is an issue with Intel GPUs. The issue appears when running on both Intel Arc A750 and Intel HD Graphics 620.

### Reproduction

1. Open the affected model in Inochi Creator.
   - The model has been [DM'ed to Luna](https://discord.com/channels/@me/1102881931588280370/1102882637703548949).
3. Observe missing right eye.

### System Architecture

x86_64

### Operating System

Linux

### Version

0.8 RC2

### Additional Context

In 0.8 RC 2:
![image](https://user-images.githubusercontent.com/106203125/235634379-0899a21b-ab45-4495-89d9-8d3a3db1ac18.png)

In 0.7.1.4:
![image](https://user-images.githubusercontent.com/106203125/235634395-8eab1612-0dd1-474e-8601-48fccfcd0258.png)

In Session 0.8 RC 1 with the irises relayered:
![image](https://user-images.githubusercontent.com/106203125/235634415-6c8eb14b-58ba-4333-bdfa-8188c640eadb.png)

**Comment by ExpiredPopsicle** [comment]
Intel Arc is on the way to Luna to test with.

**Comment by LunaTheFoxgirl** [comment]
This should be fixed now, closing unless it crops up again.
