### ISSUE TITLE
[BUG] inability to delete a parameter from the timeline using the [X]

### ISSUE THREAD

**Issue by LordLumineer** [Inochi2D/inochi-creator#267]
### Validations

- [X] I have checked for similar bug reports and could not find any.
- [X] I have tested and confirmed that this is an issue in an official branded build.

### Describe the bug

In the timeline for animation when I click on the [X] nothing happens, i believe it's supposed to delete it from the animation, the only why I found was the right click then delete.

### Reproduction

1. have so parameter set up,
2. be in edit animation
3. create an animation
4. parameter to the animation
5. click on the [X]

### System Architecture

x86_64

### Operating System

Windows

### Version

0.8

**Comment by LunaTheFoxgirl** [comment]
The X is not a button to delete, it tells you which axis the lane applies to, for 2D parameters 2 lanes are created, one for X and one for Y.
