### ISSUE TITLE
Build the Linux binary on an older distro for better binary compatibility

### ISSUE THREAD

**Issue by peat-psuwit** [Inochi2D/inochi-creator#27]
I've downloaded the Linux binary for innochi-creator for 0.7.1 to run on Ubuntu 20.04. Upon execution, the following error is printed:

```
$ ./inochi-creator 
./inochi-creator: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by ./inochi-creator)
./inochi-creator: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by ./inochi-creator)
./inochi-creator: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by ./inochi-creator)
```

This is because Ubuntu 20.04 ships with GLibc 2.31, but the machine which builds this binary probably has GLibc 2.34 or newer. This is somewhat known issue for binary compatibility in Linux: a binary compiled on a newer distro might not run on older distros.

To solve this, the binary has to be built on the oldest Linux distribution supported. This is usually some form of a long-term-support distro a few versions back. For example, Debian 10, Ubuntu 18.04 LTS, and Rocky OS 8 (based on RedHat Enterprise Linux 8) is a good candidate here.

Also, while you're at it, maybe it's a good time to investigate into using CI to automatically build the binary, which should increase trust in the binary. Since we're on GitHub, GitHub Actions is not a bad choice. It supports Ubuntu 18.04 LTS (and Windows) out of the box and allows you to upload the build results directly as release artifacts. As a bonus, users would be able to get the binary for latest development code right away.

**Comment by LunaTheFoxgirl** [comment]
We plan to eventually use CI to build AppImages for this reason. I do not have the time to build it on an older distro my self as of current, but there is starting to be work done in the CI integration.

**Comment by LunaTheFoxgirl** [comment]
We now build AppImages on the oldest supported Ubuntu LTS release provided by GitHub CI.
