### ISSUE TITLE
[BUG] German language displaying twice and with a filepath

### ISSUE THREAD

**Issue by Grat10borg** [Inochi2D/inochi-creator#273]
### Validations

- [X] I have checked for similar bug reports and could not find any.
- [X] I have tested and confirmed that this is an issue in an official branded build.

### Describe the bug

Inside Inochi creator going to change language in settings, the german language option is displaying twice and with a filepath afterward.
Note: Inochi is on installed on a PCIe NVMe SSD & not installed on the same drive windows is on

![image](https://user-images.githubusercontent.com/109081987/236899293-58de8e50-527f-42a1-9ce9-4c0f4ee99176.png)

### Reproduction

1. Open Inochi creator
2. Edit -> Settings
3. Change language in selectbox

### System Architecture

None

### Operating System

Windows

### Version

8.0

**Comment by ExpiredPopsicle** [comment]
This is working as intended. It shows the file path if there are two language tags with the same language.

**Comment by Grat10borg** [comment]
ah i see, my bad then
