### ISSUE TITLE
[BUG] (flashing warning) rotating a big node close to the centerpoint makes it rotate extremely quickly

### ISSUE THREAD

**Issue by Grat10borg** [Inochi2D/inochi-creator#280]
### Validations

- [X] I have checked for similar bug reports and could not find any.
- [X] I have tested and confirmed that this is an issue in an official branded build.

### Describe the bug

if you have a node with a large amount of stuff in it and rotate it to close to the center of the rotation point the rotating will speed up and rotate quicker and quicker instead of rotating to where the mouse is.

i'm unsure if this and the resize 0 by 0 mesh problem discribed [Here](https://github.com/Inochi2D/inochi-creator/issues/279) is the same problem here.

https://github.com/Inochi2D/inochi-creator/assets/109081987/6c14f365-629b-4857-a179-144ab2c6947b

### Reproduction

1. create a large node with lots of nodes below it
2. use on-screen rotate button
3. move your cursor close to the center of the rotation point

### System Architecture

None

### Operating System

Windows

### Version

0.8

**Comment by LunaTheFoxgirl** [comment]
@seagetch you implemented this feature, is it due to some sort of rounding for smaller resolution stuff or something?

**Comment by seagetch** [comment]
Maybe I failed to implement handling between -180 deg and 180 deg.
It should be switched seamlessly, but current implementation may have some bugs around it, I guess.

**Comment by LunaTheFoxgirl** [comment]
> Maybe I failed to implement handling between -180 deg and 180 deg. It should be switched seamlessly, but current implementation may have some bugs around it, I guess.

Internally Inochi2D uses radians, not degrees, maybe that's why?

**Comment by LunaTheFoxgirl** [comment]
Should be fixed by https://github.com/Inochi2D/inochi-creator/pull/285
