### ISSUE TITLE
[BUG] first parameter grouping refuses to delete

### ISSUE THREAD

**Issue by Grat10borg** [Inochi2D/inochi-creator#281]
### Validations

- [X] I have checked for similar bug reports and could not find any.
- [X] I have tested and confirmed that this is an issue in an official branded build.

### Describe the bug

when grouping two parameters for the first time they make group, but the first one always refuses to delete, any other groupings after the first group deletes just fine.

https://github.com/Inochi2D/inochi-creator/assets/109081987/b38966b4-48ea-4244-bcb4-1a7ababbe386

### Reproduction

1. create two parameters
2. make them into a group
3. try to delete group

### System Architecture

None

### Operating System

Windows

### Version

0.8

**Comment by LunaTheFoxgirl** [comment]
Fixed by https://github.com/Inochi2D/inochi-creator/commit/6f2b0ec3cdd4cb79d477f9c08cb7cd564b6594f4
