### ISSUE TITLE
[Feature Request] make CRTL + Z remember node's sorting when reverting

### ISSUE THREAD

**Issue by Grat10borg** [Inochi2D/inochi-creator#282]
### Validations

- [X] I have checked for similar feature requests and could not find any.
- [X] I have made sure this is not an already-existing feature.

### Description

When using inochi CRTL + Z reverts everything but the sorting when reverting a wrong node and such. 
this places something like hair on sorting -46, making it above everything else

![image](https://github.com/Inochi2D/inochi-creator/assets/109081987/3e896af2-fca8-47bb-9d86-0c88e445da84)

### Suggested solution

make it remember its orginal sorting for a few changes, incase the user wants to revert the changes

**Comment by LunaTheFoxgirl** [comment]
This bug is fixed by https://github.com/Inochi2D/inochi-creator/commit/e046cf4caef242676387dd3f05b9961c807393f0, depends on https://github.com/Inochi2D/inochi2d/commit/bdc591b97cafe3822cee7f86b01ee6d8695407ef.

**Comment by mienaiKnife** [comment]
I'm having a similar problem right now where I parented one part node to another, hit Ctrl Z to undo, and it changed the sorting value of the part that I'd just dragged and dropped. I am using version 0.8.3 on Windows
