### ISSUE TITLE
[BUG] double clicking a node does not zoom ind on low res models.

### ISSUE THREAD

**Issue by Grat10borg** [Inochi2D/inochi-creator#283]
### Validations

- [X] I have checked for similar bug reports and could not find any.
- [X] I have tested and confirmed that this is an issue in an official branded build.

### Describe the bug

double clicking a node focuses it and zooms in on the part/node clicked, 
on low res models this doesn't work and instead zooms out or just stays far away

https://github.com/Inochi2D/inochi-creator/assets/109081987/b651c45c-6d31-485e-b5a1-0cd24e7780fd

### Reproduction

1. open up a low res model file
2. double click on a node

### System Architecture

None

### Operating System

Windows

### Version

0.8

**Comment by LunaTheFoxgirl** [comment]
As far as I remember this is intentional. Trying to avoid too rapid movement that might be discomforting to the end user.

**Comment by Grat10borg** [comment]
ahh good point. nevermind then
