### ISSUE TITLE
[BUG] crash after clicking Configure Flip Pairings

### ISSUE THREAD

**Issue by amelielavender** [Inochi2D/inochi-creator#286]
### Validations

- [X] I have checked for similar bug reports and could not find any.
- [X] I have tested and confirmed that this is an issue in an official branded build.

### Describe the bug

on 0.8 stable and latest nightly [cebb76f](https://github.com/Inochi2D/inochi-creator/commit/cebb76fbe94f9c89cbfbd871b02dffbe53c11761): this doesn't happen on a newly imported .psd file. i can go into the flip pairings menu and create pairs any way i like. however, something in a rigged model causes Creator to segfault when attempting to open this window. i'm not sure what it is. 

i have tried on my own model and Aka.inx both with their newly imported .psds and with my model (partially rigged) and Aka's example model.

i'm not a dev by any means, but i did have gdb already installed so i attached a log of what it said. 

### Reproduction

1. have rigged model with armed parameters, finished or otherwise
2. try to configure flip pairings
3. app closes

### System Architecture

x86_64

### Operating System

Linux

### Version

0.8.0

### Logs

<details>
<summary>Click to expand!</summary>

```
GLInfo:                                                                                                                                                    
	3.2.0 NVIDIA 530.41.03
	NVIDIA Corporation
	NVIDIA GeForce GTX 1070/PCIe/SSE2
	1.50 NVIDIA via Cg compiler
	gls=gl32
[New Thread 0x7ffff0eba6c0 (LWP 22765)]
[New Thread 0x7ffff07866c0 (LWP 22766)]
[New Thread 0x7ffff07766c0 (LWP 22767)]
[New Thread 0x7ffff07666c0 (LWP 22768)]
[New Thread 0x7ffff07566c0 (LWP 22769)]
[New Thread 0x7ffff07466c0 (LWP 22770)]
[New Thread 0x7ffff07366c0 (LWP 22771)]
[Detaching after fork from child process 22772]

Thread 1 "inochi-creator" received signal SIGSEGV, Segmentation fault.
0x00005555555d1ad1 in _D7creator7windows10flipconfig14FlipPairWindow8pairViewMFZv (this=0x7ffff6f68b00) at source/creator/windows/flipconfig.d:257
Downloading source file /home/runner/work/inochi-creator/inochi-creator/source/creator/windows/flipconfig.d
257	source/creator/windows/flipconfig.d: Directory not empty.  
```

</details>

**Comment by LunaTheFoxgirl** [comment]
Seems to possibly be string corruption causing invalid text to be in the part name, not sure what to do there...

**Comment by amelielavender** [comment]
actually, i do remember merging psds on my own model and some visibly garbage characters appearing. the example models didn't have that in common so i didn't consider that as a reason for creator crashing...

**Comment by ExpiredPopsicle** [comment]
Fixed in c12ba916f2ae7008bff15ee4941a3e03c621e79d .

**Comment by amelielavender** [comment]
if that were the case, it wouldn't be happening on nightly builds, right?

**Comment by LunaTheFoxgirl** [comment]
> if that were the case, it wouldn't be happening on nightly builds, right?

Is it still happening in nightly builds? If so I am failing to reproduce the issue currently.

**Comment by amelielavender** [comment]
> Is it still happening in nightly builds? If so I am failing to reproduce the issue currently.

just tried it on latest flatpak as well as the standalone binary and it segfaults for me me on my own model, but it's fixed on the example models. i can upload the model i'm working on if needed. 

https://github.com/Inochi2D/inochi-creator/assets/26533281/6cd5b16a-7058-4d69-9710-5cacb0b883a0
