### ISSUE TITLE
[BUG] File corruption

### ISSUE THREAD

**Issue by Almarane** [Inochi2D/inochi-creator#294]
### Validations

- [X] I have checked for similar bug reports and could not find any.
- [X] I have tested and confirmed that this is an issue in an official branded build.

### Describe the bug

I have two nodes : "bouche lineart bas" for the lower lip's lineart ("lineart" in the following text), and "bouche bas" for the skin to cover up the mouth's inner parts ("skin" in the following text).
I copy/pasted the meshes from the lineart to the skin, then I created a new Parameter "bouche" to deform the lineart. Then, I copy/pasted the lineart's deform to the skin. Afterwards, I edited the skin's meshes to add extra points so it'll display the whole skin.
I saved and closed, but when I re-opened it it gave me this error : 

![Capture d’écran 2023-07-04 190627](https://github.com/Inochi2D/inochi-creator/assets/11445580/304bf7d5-3f8f-4156-a3b8-0475f3c41b76)

I can't seem to reproduce it with Aka's model though.

After recovering the file with INPUnpack, using "Save As" or edditing the skin's meshes make the error appear once again.

### Reproduction

First occurence of the error : 

1. Copy/paste layer A's meshes to layer B.
2. Apply a parameter deformation to A.
3. Copy/paste A's deformation to B.
4. Edit B's meshes to add extra points and triangles.
5. Save the project
6. Close the project
7. Open the project
-> error appears

"Save as" occurence : 

1. Restore the file with INPUnpack by adding extra quotes to the "nan"s.
2. Open the restaured file
3. Use "File > Save As"
4. Close the project
5. Open the "saved as" project
-> error appears

### System Architecture

None

### Operating System

Windows

### Version

0.8.1-rc2

### Additional Context

The files : 
[files.zip](https://github.com/Inochi2D/inochi-creator/files/11951513/files.zip)

corrupted.inx -> the file when it was first corrupted
restaured.inx -> file fixed with INPUnpack
corrupted_save_as -> file fixed then corrupted again by using "Save As"

**Comment by Almarane** [comment]
May have been fixed by https://github.com/Inochi2D/fghj/commit/cb73df65e289c820e801c62401c8048c03c806bf

**Comment by LunaTheFoxgirl** [comment]
Fixed by https://github.com/Inochi2D/fghj/commit/cb73df65e289c820e801c62401c8048c03c806bf and https://github.com/Inochi2D/inochi-creator/commit/1edc1834b2f8648ba695e651ebfc5da88c2b5a4b in my local testing.
