### ISSUE TITLE
[BUG] Crash when removing a vertex with no symmetrical vertex on mirror mode

### ISSUE THREAD

**Issue by Almarane** [Inochi2D/inochi-creator#295]
### Validations

- [X] I have checked for similar bug reports and could not find any.
- [X] I have tested and confirmed that this is an issue in an official branded build.

### Describe the bug

While editting meshes with "Mirror Horizontally" enabled, removing a vertex with no symmetrical makes Inochi Creator crash.

### Reproduction

1. Select a layer
2. Click "Edit Mesh"
3. Create a vertex anywhere
4. Click "Mirror Horizontally"
5. Remove the vertex created during Step 3
-> App crash

### System Architecture

None

### Operating System

Windows

### Version

0.8.0

**Comment by seagetch** [comment]
Maybe this bug is fixed by https://github.com/Inochi2D/inochi-creator/pull/292
Please check nightly build.

**Comment by LunaTheFoxgirl** [comment]
Issue is fixed in my testing, closing.
