### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by CaliberDied** [Inochi2D/inochi-creator#297]
### Validations

- [X] I have checked for similar bug reports and could not find any.
- [X] I have tested and confirmed that this is an issue in an official branded build.

### Describe the bug

When saving a mesh in a mesh group, Inochi2D crashes.

### Reproduction

1. Selected Mesh Group
2. Created Grid Vertex Mesh
3. Clicked on Apply
4. Crash

### System Architecture

x86_64

### Operating System

Windows

### Version

0.8.1rc3

### Logs

<details>
<summary>Click to expand!</summary>
```
=== Args State ===


=== Exception ===
core.exception.ArrayIndexError@source\creator\viewport\common\mesh.d(988): index [0] is out of bounds for array of length 0
----------------
0x00007FF746D76E54 in ImFontAtlas_SetTexID
0x00007FF746D76B94 in ImFontAtlas_SetTexID
0x00007FF746D752FD in ImGuiInputTextState_GetSelectionStart
0x00007FF746D68A11 in ImGuiInputTextState_GetSelectionStart
0x00007FF746D55914 in ImGuiInputTextState_GetSelectionStart
0x00007FF746D57392 in ImGuiInputTextState_GetSelectionStart
0x00007FF746D57665 in ImGuiInputTextState_GetSelectionStart
0x00007FF746BFDBAF in igImAbs_Float
0x00007FF746BFD342 in igImAbs_Float
0x00007FF746BF6567 in igImAbs_Float
0x00007FF746BF6479 in igImAbs_Float
0x00007FF746BF56B3 in igImAbs_Float
0x00007FF746BEF7C0 in igImAbs_Float
0x00007FF746D52DDD in ImGuiInputTextState_GetSelectionEnd
0x00007FF746BDA9E5
0x00007FF746BDA3D6
0x00007FF746C072AC in igImAbs_Float
0x00007FF746C89337 in ImGuiDockNode_IsSplitNode
0x00007FF746C89111 in ImGuiDockNode_IsSplitNode
0x00007FF746D5CED5 in ImGuiInputTextState_GetSelectionStart
0x00007FF746D5CB61 in ImGuiInputTextState_GetSelectionStart
0x00007FF746D5CE33 in ImGuiInputTextState_GetSelectionStart
0x00007FF746E179D0 in ImGui_ImplOpenGL3_Shutdown
0x00007FFFFDF07614 in BaseThreadInitThunk
0x00007FFFFE0426F1 in RtlUserThreadStart
```
</details>

**Comment by grillo-delmal** [comment]
Tried to reproduce on Linux but failed... does the procedure in this video produces a crash for you? or do you do anything else besides that?

[mesh_group_vertex_mesh.webm](https://github.com/Inochi2D/inochi-creator/assets/11585030/bd1e2333-d470-4bea-beae-a49007a4680d)

**Comment by CaliberDied** [comment]
The procedure does not crash for me. I somehow resolved it. The steps I
took to resolve it involved removing (I think you might be able to
unset/reset as well) the mesh group from one of the parameters, and then
proceeding to make the mesh.

**Comment by LunaTheFoxgirl** [comment]
I think I'll need a minimal reproducable example file to fix this one, I'm not sure I'll be able to fix it before we release 0.8.1, so it might need to first be fixed for 0.9.

**Comment by CaliberDied** [comment]
I still have the file that reproduces the error and crash, I can send it to
you if you want it.

**Comment by CaliberDied** [comment]
[poop.webm](https://github.com/Inochi2D/inochi-creator/assets/93340197/792d1bc9-1cb1-4d36-9890-5099a6e084d5)

**Comment by LunaTheFoxgirl** [comment]
If you could send the file to dev@inochi2d.com then I can look in to it.

**Comment by LunaTheFoxgirl** [comment]
This bug goes really deep and it's @seagetch's code from what I can tell and I don't fully understand how it gets in to this invalid state. As such a fix for this issue has to be pushed out to 0.9.

**Comment by seagetch** [comment]
Okay, I have no time to look in details.
I think it should be labeled 0.8 series.
and should be fixed shortly after releasing 0.8.1

**Comment by seagetch** [comment]
@CaliberDied 
I want to clarify the problem.

Is application crashed whenever applying mesh groups to newly created MeshGroup?
Or is it happening just for problematic MeshGroup?
If it happened only for certain MeshGroup, maybe some garbage information remained, and that led to crash.

Moving all child of MeshGroup to parent of the MeshGroup once, removing MeshGroup and recreate it, and moving all of the children to the new MeshGroup might avoid the crash.
(That's only workaround solution, though.)

**Comment by LunaTheFoxgirl** [comment]
> Okay, I have no time to look in details now. I think it should be labeled 0.8 series. and should be fixed shortly after releasing 0.8.1

In that case you can develop the fix for the v0_8 branch; then we forward port it to 0.9.

**Comment by CaliberDied** [comment]
It is occurring whenever there is a change in any MeshGroup. From applying
a mesh to a MeshGroup that previously did not have a mesh, to modifying a
MeshGroup that already exists. This only applies to MeshGroups, I could not
replicate the crash with individual layers. My workaround solution involved
removing the MeshGroup from one of the parameters, as it fixed everything
thereafter.

**Comment by seagetch** [comment]
@CaliberDied 
thank you for more details.maybe
> From applying
a mesh to a MeshGroup that previously did not have a mesh,
is the easiest to reproduce. I'll try it later.

**Comment by seagetch** [comment]
I sent PR https://github.com/Inochi2D/inochi-creator/pull/301 for this bug.
I believe this patch fix the problem.
