### ISSUE TITLE
[Feature Request] Free lasso tool to select vertices

### ISSUE THREAD

**Issue by rongjie-alter** [Inochi2D/inochi-creator#314]
### Validations

- [X] I have checked for similar feature requests and could not find any.
- [X] I have made sure this is not an already-existing feature.

### Description

Currently we only have box select tool to select vertices.

### Suggested solution

It would be great to have "free lasso tool" to select vertices

By default it is to "select more vertices and add into current selection"
Holding Alt key would switch to "deselect vertices from current selection"
Click a button to cancel current selection

The last two functionality should be applied for the original "box select tool" too

**Comment by rongjie-alter** [comment]
In a way, box and lasso are just two tools under selection mode

**Comment by r888800009** [comment]
I think the solution has two parts
1. How to implement a stateful mesh pen, which means we can switch to `lasso mode` to generate a selected set of vertices
2. Then we can implement point in polygon (PIP) algorithm to generate a set of selected lists covering the state of mesh pen

**Comment by r888800009** [comment]
The selection is maintained by `IncMeshEditorOne` and the implementation is separate from the tool, so we should be able to add a new pen for `lasso mode`
