### ISSUE TITLE
Investigate egui as a plausible alternative to imgui

### ISSUE THREAD

**Issue by LunaTheFoxgirl** [Inochi2D/inochi-creator#32]
There's this Rust library called egui that seems to handle some of our essential needs a lot better than imgui can currently. We should evaluate whether we want to create a Rust->D/C binding for egui to use it with Inochi Creator for the next complete refactor.

Project can be found here: https://github.com/emilk/egui

Pros:
 * It's not written in C or C++, and thus is not a nightmare to build
 * Seems to support multilingual use a lot better than imgui currently does
 * Has more styling options.

Cons:
 * Has no docking or viewports (currently, at least)
 * Project seems to not care about using it outside of Rust, so we may not get support. (rewriting in Rust is _not_ an option)
 
 Considerations made already:
 * Rust, like D uses fat pointers to store strings with the same memory layout as D; as such as long as we don't care about direct C compatibility we should be able to save some overhead from constantly adding null terminators to strings in our UI rendering code.
 * egui seems to have WIP support for screen readers which is a nice-to-have
 * egui seems to be able to dynamically load font glyphs while rendering, allowing us to properly support localization (**IMPORTANT**)
 * There will be some downtime from converting Inochi Creator over to egui; but that would be there anyways as I'm working on our own UI middleware for handling all of the window and widget setup and such for Inochi2D apps.

**Comment by playmer** [comment]
Would the thought be to generate a C API for egui and then we bind that?

**Comment by LunaTheFoxgirl** [comment]
More or less, but without the header files, we would also statically link to egui instead. Meaning no bindbc for this one.

**Comment by LunaTheFoxgirl** [comment]
Not really, the core problem building cimgui is that it's C/C++ and a mix of libraries that end up being anoying to build in a Linux friendly way without something breaking.

egui has the advantage that we can just use cargo to handle the building, then link against the output library. Reason why egui would be statically linked is because Rust afaik doesn't support dynamic linking.

**Comment by LunaTheFoxgirl** [comment]
I feel that the thing we should trial egui on is Inochi Session, if it works well there then we can look in to how feasible it would be in Inochi Creator, is important that egui wouldn't make the workflow worse.

**Comment by LunaTheFoxgirl** [comment]
We're not moving to egui as the pattern does not work well for C-like applications
