### ISSUE TITLE
[BUG] Crash on Windows 10 after transforming camera view port then trying to export

### ISSUE THREAD

**Issue by MikeyMasu** [Inochi2D/inochi-creator#329]
### Validations

- [X] I have checked for similar bug reports and could not find any.
- [X] I have tested and confirmed that this is an issue in an official branded build.

### Describe the bug

Tried to export video without animations (I'm new to the camera tool and was experimenting), resulting in an Inochi Creator Crashdump.
I actually did this once before and all it did was tell me `No animations are defined for this model, please add an animation.`

This time it immediately gave me Inochi Creator Crashdump dialog.
I tried a second time just to see if this was able to be replicated, resulted in the `No animations are defined` dialog, followed half a second later by the Crashdump dialog.

To be clear, I'm sure this was user error, but I still thought I should report it.

### Reproduction

**INITIAL**
1. Added a camera child to a regular parent node.
_(Note: Parent node was not the Puppet Node, it was nested 3 nodes below the puppet node. I'll add a screenshot to show what I'm talking about.*)_
2. Adjust the camera boundary using the movable, in frame, scale tool.
3. Notice the numbers under Camera Viewport haven't changed to reflect the boundary movements.
_(Note: I had used the scale tool to move the boundary box to more of a 4:3 ratio while the Camera Viewport numbers still read for a 16:9 ratio.)_
4. When I did go to change the numbers from 1920x1080 to something else, the already adjusted boundary box lines started to move.
5. File > Export > Video, to see what other steps I needed to complete
_(Note: This was my first time with using this tool.)_
6. Option to name and save appear. Named it `test_example.mp4`.
7. Crash dialogue appeared said to report it here and provide the crash dump.

**REPRODUCED**
_Only difference was the result**_
7. `Error: No animations are defined for this model, please add an animation. OK` dialog appeared, followed by `Inochi Creator Crashdump` dialog after half second delay.

### System Architecture

None

### Operating System

Windows

### Version

0.8.3

### Additional Context

*The highlighted spots is the node hierarchy I was talking about.
**The screenshot is from the reproduction.
![image](https://github.com/Inochi2D/inochi-creator/assets/145874053/2c7ea938-1760-4d7f-8b6a-b22adce8dad8)

Only 1 crash dump to give. I don't know if the reproduction overwrote the original crash, or if it just added to it.
https://github.com/Inochi2D/inochi-creator/files/14184236/inochi-creator-crashdump.txt

**Comment by r888800009** [comment]
There are two possibilities for the crash. One is that the camera has an odd size, and the other is a problem that has been fixed in PR https://github.com/Inochi2D/inochi-creator/pull/393.
