### ISSUE TITLE
[BUG] Crashes sometimes when pasting parameters with horizontal flip

### ISSUE THREAD

**Issue by licoreart** [Inochi2D/inochi-creator#336]
### Validations

- [X] I have checked for similar bug reports and could not find any.
- [X] I have tested and confirmed that this is an issue in an official branded build.

### Describe the bug

So, sometimes, when pasting parameters with horizontal flip, the program crashes. Was following this tutorial: https://youtu.be/5hzo0d-Zzi4?si=dQAuGoFn9Vo9JMk_&t=1377 and the software crashed for them, so I saved mine. And it crashed too.

### Reproduction

1. Copy parameters
2. Paste with horizontal flip

### System Architecture

x86_64

### Operating System

Windows

### Version

0.8.4

**Comment by grillo-delmal** [comment]
Ok, I was able to reproduce this :) it crashes when you save a flip pairing without a pair and try to copy around deformations.
As the reporter says, it also affects version 0.8.4

**Comment by grillo-delmal** [comment]
Searched a bit more and the bug is more generic, it crashes whenever it tries to look for a pair of an element that is either not in the pair list or lower in the unpaired list.

**Comment by grillo-delmal** [comment]
Here is a model that reproduces the problem
[eyes.inx.zip](https://github.com/Inochi2D/inochi-creator/files/14602570/eyes.inx.zip)
