### ISSUE TITLE
[Feature Request] Ability to swap XY output for physics

### ISSUE THREAD

**Issue by Draconizations** [Inochi2D/inochi-creator#337]
### Validations

- [X] I have checked for similar feature requests and could not find any.
- [X] I have made sure this is not an already-existing feature.

### Description

Hopefully the attached video should help explain-- I'm not sure how to word this best.

I'm trying to rig a parameter that controls the head angles through physics. The head angle tracking input would be bound to this, rather than directly to the output. something like what this video describes https://youtu.be/tU-a_quY7Ko?si=uZ67VYgixTClZuja but for inochi2D (although I'm using XY mappings rather than anglelength, since anglelength didn't seem to give the results I wanted. assuming this is just a fundamental difference between inochi2D and live2D)

currently I have two parameters, one for X, one for Y, as well as two physics nodes for X and Y. the head angle output is bound to both of these physics nodes.

my issue is that when moving a mapped pendulum up and down, there seems to be no way to mimic the behavior of moving an XY mapped pendulum on the X axis. When moving the pendulum sideways, the pendulum's resting point moves, this is what I want so the head can remain looking sideways. When moving the pendulum up and down on the Y axis, the resting point remains the same and eventually the head won't be tilted up or down anymore.

https://github.com/Inochi2D/inochi-creator/assets/72747870/ea82747a-afb7-421a-805a-03e28c468897

### Suggested solution

The ability to swap the output of an XY physics node to the mapped parameter. So that the pendulum's X input will map to the parameter's Y output, and vice versa.

That way the current behavior for XY physics can remain the same while solving this specific use-case!

### Alternative solution

I did figure out that I could separate the output head angles into two 1-dimensional parameters, for both X and Y, then map the two parameters to those independently. The issue with this is that any rigging bound to the corners of the angles will be lost. Often the interpolation between the two isn't quite where I want it to be.

I'm trying to avoid having to change the way XY mapping works here or having to make a whole new mapping type since I think the proposed solution is elegant enough if possible.

**Comment by grillo-delmal** [comment]
Wouldn't you get the expected result by flipping the `Head Angles` parameter on the Y axis?

![image](https://github.com/Inochi2D/inochi-creator/assets/11585030/17996ad7-1ab5-413e-8279-ec724705764a)

**Comment by Draconizations** [comment]
(I replied to this on discord, copy and pasting the conversation here)

That would flip the movement but not fix the issue I'm having.

From my observations the following applies
- when locking to local transform only, moving the pendulum on the X axis moves the output. So if i move the pendulum by 60X and the output scale is 1.0, the new "baseline" or resting pointfor the pendulum's X output is 60.
- this does not apply to Y. When locked to local transform with Y, regardless of whether the pendulum is a spring pendulum or not, there is no visible change at all. Only if the local transform lock is unchecked, and the pendulum is a springpendulum, theres a bouncing effect
- however the resting point doesnt change! Eventually the face will not be tilted up or downwards anymore, while it stays at the correct position when looking to the left or right

My issue is with the resting point not changing. But i wouldnt want to change physics behavior drastically either, so being able to map the X input of a pendulum to the Y output of the parameter would be nice

**Comment by grillo-delmal** [comment]
oh, now I see, I misunderstood what the main issue was cos the video had the head movement flipped by the Y axis xD

**Comment by grillo-delmal** [comment]
This can get closed since the feature was implemented and is available on 0.8.5
