### ISSUE TITLE
[BUG] Fallback top window border in Gnome Wayland

### ISSUE THREAD

**Issue by PolyCatDev** [Inochi2D/inochi-creator#340]
### Validations

- [X] I have checked for similar bug reports and could not find any.
- [X] I have tested and confirmed that this is an issue in an official branded build.

### What is happening?
I am opening Inochi Creator from the official Flathub page and I get the fallback top header instead of the gnome one. 

### Why?
From my understanding, this is because Gnome doesn't support Server Side Decorations on Wayland.

### Image:
![Screenshot from 2024-03-04 21-39-20](https://github.com/Inochi2D/inochi-creator/assets/88086950/4344e6a8-0130-43d6-8a4a-aa875c5ffa53)

### Reproduction

Just launch Inochi Creator from Flahub on Gnome Wayland.

### System Architecture

x86_64

### Operating System

Linux

### Version

0.8.4 from Flathub

### Logs

$ flatpak run --verbose com.inochi2d.inochi-creator

F: No installations directory in /etc/flatpak/installations.d. Skipping
F: Opening system flatpak installation at path /var/lib/flatpak
F: Opening user flatpak installation at path /home/polycat/.local/share/flatpak
F: Opening user flatpak installation at path /home/polycat/.local/share/flatpak
F: Opening system flatpak installation at path /var/lib/flatpak
F: Opening user flatpak installation at path /home/polycat/.local/share/flatpak
F: Opening system flatpak installation at path /var/lib/flatpak
F: /var/lib/flatpak/runtime/org.freedesktop.Platform/x86_64/22.08/5ac49ce502b33a263af052c0b66aaddb6874df4259292ec9a2b912021d7e9cd8/files/lib32 does not exist
F: Cleaning up unused container id 3216669146
F: Allocated instance id 1463152878
F: Add defaults in dir /com/inochi2d/inochi-creator/
F: Add locks in dir /com/inochi2d/inochi-creator/
F: Disallowing network access
F: Allowing host-fs access
F: Allowing wayland access
F: Running '/usr/bin/bwrap --args 39 /usr/bin/xdg-dbus-proxy --args=41'
F: Running '/usr/bin/bwrap --args 39 inochi-creator'

**Comment by grillo-delmal** [comment]
Its using SDL2 as a decoration backend, so it's working as expected

**Comment by PolyCatDev** [comment]
Oh, ok. Should I just close this issue then?

**Comment by PolyCatDev** [comment]
Working as expected
