### ISSUE TITLE
[BUG] Enabling both 'Enable Transparency' and 'Use Post Processing' when exporting to PNG causes output background to be solid black

### ISSUE THREAD

**Issue by helloar14** [Inochi2D/inochi-creator#342]
### Validations

- [X] I have checked for similar bug reports and could not find any.
- [X] I have tested and confirmed that this is an issue in an official branded build.

### Describe the bug

As per title said, enabling both 'Enable Transparency' and 'Use Post Processing' when exporting to PNG causes output background to be solid black. Enabling 'Enable Transparency' only produces correct image with transparent background.

I'm not sure if this a bug or intended behavior. If it's intended behavior, maybe make the 'Enable Transparency' checkbox disabled when 'Use Post Processing' is checked.

Transparency only:

![transparency](https://github.com/Inochi2D/inochi-creator/assets/7506276/3cbe655c-88d1-4bfe-932e-7d02961ba31e)

Transparency and post processing:

![transparency-postprocessing](https://github.com/Inochi2D/inochi-creator/assets/7506276/499f66e4-cc21-4fc2-822a-fdd56553c175)

### Reproduction

Export to PNG with different settings:
1. Both 'Enable Transparency' and 'Use Post Processing' checked;
2. Only 'Enable Transparency' checked.

### System Architecture

x86_64

### Operating System

Windows

### Version

0.8.0

**Comment by ShadowMarker789** [comment]
@helloar14 

Couldn't replicate on 0.8.4-3-ge2bda33 using axa.inx file. 

![Screenshot of setup](https://github.com/Inochi2D/inochi-creator/assets/37165910/d8f65389-4baa-469b-bce6-cc99adcb9929)

![Export options](https://github.com/Inochi2D/inochi-creator/assets/37165910/d07e1083-b890-4c3b-8727-676d3c079523)

![Exported Image](https://github.com/Inochi2D/inochi-creator/assets/37165910/37d848bc-be43-42c1-b63d-1ed90db45d1d)

Could it be that this only applies when one has post-processing effects? 

Is there a sample minimum-reproducing INX file you can provide?

**Comment by helloar14** [comment]
Wait you're right. I'll try to check out what is the problem with my model first.

**Comment by helloar14** [comment]
So I tried again and indeed Aka.inx is working well with post processing.

Since I use 0.8.0 as my daily driver now I tried to switch to 0.8.4. Still the same with my model, and still working correctly with Aka.

However, I tried making a new file from scratch and somehow this issue is reproduced:


https://github.com/Inochi2D/inochi-creator/assets/7506276/0f0a3def-61cb-4ad0-9b40-fbf98c98fa84

EDIT: Tried again, now using the PSD import feature, still the same:


https://github.com/Inochi2D/inochi-creator/assets/7506276/eb836273-8cb8-461f-87c8-e6b67ce6967d

**Comment by ShadowMarker789** [comment]
> So I tried again and indeed Aka.inx is working well with post processing.
> 
> Since I use 0.8.0 as my daily driver now I tried to switch to 0.8.4. Still the same with my model, and still working correctly with Aka.
> 
> However, I tried making a new file from scratch and somehow this issue is reproduced:
> 
> EDIT: Tried again, now using the PSD import feature, still the same:
> 

Thanks for your help in reproducing it, fix in https://github.com/Inochi2D/inochi2d/pull/59 

The glClearColor was never set, so it defaulted to `0.0, 0.0, 0.0, 1.0` - fully opaque black.
