### ISSUE TITLE
[BUG] Build Process broke because Enum ParamMapMode.LengthAngle and ParamMapMode.YX dont exist in [inochi2d/tree/v0.8.3]

### ISSUE THREAD

**Issue by gaming-se** [Inochi2D/inochi-creator#354]
### Validations

- [X] I have checked for similar bug reports and could not find any.
- [X] I have tested and confirmed that this is an issue in an official branded build.

### Describe the bug

Build Processes broke because Enum 
LengthAngle and YX dont exist in 

enum ParamMapMode {
    AngleLength = "angle_length",
    XY = "xy",
}
of 0.8.3 https://github.com/Inochi2D/inochi2d/tree/v0.8.3

added in the commit: https://github.com/Inochi2D/inochi-creator/commit/f13e671572757627f453f27d49ae792e155308e1 from https://github.com/Inochi2D/inochi-creator/pull/339/commits/33184e27ec1d6f9da0e1641e9e2f0ec6bc788d8e

The Enum Changes been added in 
https://github.com/Inochi2D/inochi2d/pull/58/commits/ad178b965b1c2be7d6ea561ef7588161a35ecd3b
and merged to https://github.com/Inochi2D/inochi2d/tree/v0_8

### Reproduction

Visit your Action list for example: 

https://github.com/Inochi2D/inochi-creator/actions/runs/8946763249/job/24577857145

scroll down to last error: 

`source\creator\panels\inspector.d(1251,65): Error: no property `LengthAngle` for type `ParamMapMode`
C:\Users\runneradmin\AppData\Local\dub\packages\inochi2d\0.8.3\inochi2d\source\inochi2d\core\nodes\drivers\simplephysics.d(40,1):        enum `ParamMapMode` defined here
source\creator\panels\inspector.d(1251,107): Error: no property `LengthAngle` for type `ParamMapMode`
C:\Users\runneradmin\AppData\Local\dub\packages\inochi2d\0.8.3\inochi2d\source\inochi2d\core\nodes\drivers\simplephysics.d(40,1):        enum `ParamMapMode` defined here
source\creator\panels\inspector.d(1253,56): Error: no property `YX` for type `ParamMapMode`. Did you mean `ParamMapMode.XY` ?
C:\Users\runneradmin\AppData\Local\dub\packages\inochi2d\0.8.3\inochi2d\source\inochi2d\core\nodes\drivers\simplephysics.d(40,1):        enum `ParamMapMode` defined here
source\creator\panels\inspector.d(1253,89): Error: no property `YX` for type `ParamMapMode`. Did you mean `ParamMapMode.XY` ?
C:\Users\runneradmin\AppData\Local\dub\packages\inochi2d\0.8.3\inochi2d\source\inochi2d\core\nodes\drivers\simplephysics.d(40,1):        enum `ParamMapMode` defined here`

### System Architecture

None

### Operating System

None

**Comment by LunaTheFoxgirl** [comment]
This is not a bug, just a release not having been sliced yet.

To fix this use dub add-local to add a git clone of the v0_8 branch to the local package registry.

**Comment by gaming-se** [comment]
i understand how to solve this, I just wanted to point out that u have a action that is wasting your cpu time 

github CPU usage (from Nightly #632 upward to Nightly #695) = 63* 9 min = 567 min CPU time 
having a nightly label that says failed in front of your build 
&nbsp;&nbsp;&nbsp;&nbsp;
[![Nightly Builds](https://img.shields.io/github/actions/workflow/status/Inochi2D/inochi-creator/nightly.yml?label=Nightly&style=for-the-badge)](https://github.com/Inochi2D/inochi-creator/releases/tag/nightly) 
 
and ppl not beeing able to test newest changes that u implemented while development without spending time into setting up **local** development envirment. i mean what about your casual non develper testers ?

**Comment by LunaTheFoxgirl** [comment]
> i understand how to solve this, I just wanted to point out that u have a action that is wasting your cpu time
> 
> github CPU usage (from Nightly #632 upward to Nightly #695) = 63* 9 min = 567 min CPU time having a nightly label that says failed in front of your build      [![Nightly Builds](https://camo.githubusercontent.com/5c050f2e5bf8dcc8e7093ed5e40aff94ee058e1fa07203e30498280e0f61c736/68747470733a2f2f696d672e736869656c64732e696f2f6769746875622f616374696f6e732f776f726b666c6f772f7374617475732f496e6f63686932442f696e6f6368692d63726561746f722f6e696768746c792e796d6c3f6c6162656c3d4e696768746c79267374796c653d666f722d7468652d6261646765)](https://github.com/Inochi2D/inochi-creator/releases/tag/nightly)
> 
> and ppl not beeing able to test newest changes that u implemented while development without spending time into setting up **local** development envirment. i mean what about your casual non develper testers ?

Current focus is on the UI rewrite so the changes to the nightly branch are _less_ relevant to test for end users at the moment.
