### ISSUE TITLE
[BUG] Video export error, and animation can't even be played in Creator

### ISSUE THREAD

**Issue by rongjie-alter** [Inochi2D/inochi-creator#368]
### Validations

- [X] I have checked for similar bug reports and could not find any.
- [X] I have tested and confirmed that this is an issue in an official branded build.

### Describe the bug

File: https://drive.google.com/file/d/1-rLXfzaEHENECf8ghOqNn3Qust61X92E/view?usp=sharing

Try play the "rub1" animation in the file, it won't play at all

Exporting .mp4 also gives this error

![image](https://github.com/Inochi2D/inochi-creator/assets/71772241/30de8fb5-2e05-488b-b919-f7bb892a3602)

### Reproduction

See above

### System Architecture

x86_64

### Operating System

Windows

### Version

0.8

**Comment by rongjie-alter** [comment]
There is also another video export issue (because the animation playing issue happened) that, the exported video file is only valid (has file size) after exiting Inochi Creator

I would prefer not having to close Inochi Creator to check the exported video file, as that would make me lose all my undo history

**Comment by rongjie-alter** [comment]
Actually you know what, my issue might be related to https://github.com/Inochi2D/inochi-creator/issues/329 , my issue also started after changing the camera viewport dimension

But mine did not crash the entire Inochi Creator

**Comment by r888800009** [comment]
Creator seems to call ffmpeg through shell command

https://github.com/Inochi2D/inochi-creator/blob/e757c746aab2fde1046f3cf5366b476e81f3e0ef/source/creator/io/videoexport.d#L87-L100

gen args

https://github.com/Inochi2D/inochi-creator/blob/e757c746aab2fde1046f3cf5366b476e81f3e0ef/source/creator/io/videoexport.d#L182

I think this may be a dependency problem, not sure if the release includes ffmpeg
Also maybe check the mp4 codec issue



> There is also another video export issue (because the animation playing issue happened) that, the exported video file is only valid (has file size) after exiting Inochi Creator

It sounds like the file resource was not closed when throwing

> Actually you know what, my issue might be related to #329 , my issue also started after changing the camera viewport dimension
> 
> But mine did not crash the entire Inochi Creator

Maybe the height and width are not updated

https://github.com/Inochi2D/inochi-creator/blob/e757c746aab2fde1046f3cf5366b476e81f3e0ef/source/creator/io/videoexport.d#L134-L136

**Comment by r888800009** [comment]
This crash seems to be reproducible on macos
