### ISSUE TITLE
WebAssembly support

### ISSUE THREAD

**Issue by ghost** [Inochi2D/inochi-creator#37]
It would be nice to have WebAssembly support, so that inochi could run in the browser.

**Comment by LunaTheFoxgirl** [comment]
This is at current time not feasible, we use the D garbage collector pretty heavily, which prevents the codebase from being compiler for webasm.

Hopefully eventually webasm will support garbage collected languages better

**Comment by Daniel8811** [comment]
Thanks.

I wonder if the GC also be compiled with some trick? 

C# works in webasm by ilcpp.
