### ISSUE TITLE
[Feature Request] Add Medibang File Support

### ISSUE THREAD

**Issue by mechPenSketch** [Inochi2D/inochi-creator#370]
### Validations

- [X] I have checked for similar feature requests and could not find any.
- [X] I have made sure this is not an already-existing feature.

### Description

When creating a new project, I would like to import Medibang (.mdp) files as an option.

### Suggested solution

On the starting splash screen, add "Import MDP" to Create Project > Import.

Also, on the topbar add "Medibang Document" to File > Import as well as File > Merge.

Medibang's layer system shouldn't be different from Photoshop or Krita's for it to be implementable.

### Alternative solution

Save or export Medibang files as .psd.

### Additional Context

Medibang might not be ideal for drawing Vtuber models due to how symmetry drawing is set by hand rather than by proportion of canvas, but it's usable to scenes and poses that aren't drawn symmetrically.

**Comment by LunaTheFoxgirl** [comment]
Without a format specification that specifies the binary layout of a mdp file I can't create an importer for it sadly. I have been unable to find any such documentation so I assume that the file format is kept proprietary.
