### ISSUE TITLE
[Feature Request] Range selection on shift+click

### ISSUE THREAD

**Issue by Wilker-uwu** [Inochi2D/inochi-creator#374]
### Validations

- [X] I have checked for similar feature requests and could not find any.
- [X] I have made sure this is not an already-existing feature.

### Description

For the tutorial example i found myself having to move multiple nodes around in the tree, but the program lacks implementation for multiple selections other than ctrl+click to select one node at a time. Being able to select multiple nodes at once would be a good qol feature.

### Suggested solution

currently, clicking a node in the node tree selects a node, and ctrl+click on a node adds or removes a node from the selection batch. with the feature, clicking any mode in any way would change the "primary" selection, and ctrl+click would keep adding and removing nodes as is the case right now.

shift+clicking would take the range between the current primary selection, and the node that was clicked.  this would allow for multiple selection ranges to be made.

### Additional Context

this is a standard feature in several programs involving some form of list selection, most notably in file managers. including an arrow key navigation of the list with all the selection features included would also be useful.

**Comment by r888800009** [comment]
This issue seems like a duplicate of #156

**Comment by Wilker-uwu** [comment]
makes sense, i'll close this then
