### ISSUE TITLE
[BUG] Copying Mesh Leads to Editing Mesh

### ISSUE THREAD

**Issue by mechPenSketch** [Inochi2D/inochi-creator#376]
### Validations

- [X] I have checked for similar bug reports and could not find any.
- [X] I have tested and confirmed that this is an issue in an official branded build.

### Describe the bug

I tried copying a Mesh, but it leads me to an interface for editing a mesh instead.

### Reproduction

Drag and drop a Mesh to Copy Mesh button.

### System Architecture

None

### Operating System

Windows

### Version

v0.8.5

### Additional Context

System type is 64-bit operating system, x64-based processor, which is not in the option of System Architecture.

**Comment by LunaTheFoxgirl** [comment]
This is intentional, it copies the mesh over and goes to the edit interface to allow you to quickly make any changes you want. To finish the copy just accept the mesh.

**Comment by mechPenSketch** [comment]
I have pressed the Accept button, but I cannot find the copied mesh anywhere in the node tree. Is it supposed to be immediately below the original? The History tab reads: "Changed drawable mesh of Mesh".

**Comment by LunaTheFoxgirl** [comment]
The copied mesh will be applied to whichever drawable node was selected when you dragged the drawable onto the "Copy Mesh" button.

**Comment by mechPenSketch** [comment]
OK, after testing it out further, I understand how "Copy Mesh" really works. I had the wrong impression that it copy-pastes a Mesh as a Node.
