### ISSUE TITLE
[Feature Request] Ability to search nodes in the node list

### ISSUE THREAD

**Issue by SkiyoshiVT** [Inochi2D/inochi-creator#400]
### Validations

- [X] I have checked for similar feature requests and could not find any.
- [X] I have made sure this is not an already-existing feature.

### Description

I would love to be able to search nodes in the node list to make it easier to find specific nodes when working on a model with a lot of layers. 

_Image created by r888800009_
<img width="330" alt="image-1" src="https://github.com/user-attachments/assets/b35dd851-ea86-4632-b6ed-1bceaa4003ee">

### Suggested solution

Textbox somewhere to search for nodes in the list. Hopefully of any kind of nodes, with a potential to search/filter by type of node.

**Comment by r888800009** [comment]
Here we can reuse the filter of parameters

https://github.com/Inochi2D/inochi-creator/blob/da1b49aaa72c5d4b70f8c27487d02ba191bce773/source/creator/panels/parameters.d#L1094-L1099

Modify this recursion

https://github.com/Inochi2D/inochi-creator/blob/da1b49aaa72c5d4b70f8c27487d02ba191bce773/source/creator/panels/nodes.d#L194
