### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by S-off-S** [Inochi2D/inochi-creator#421]
### Validations

- [X] I have checked for similar bug reports and could not find any.
- [X] I have tested and confirmed that this is an issue in an official branded build.

### Describe the bug

Hii!! Whenever I try to load a save file, an error fromString failed to parse float appears. 
![image](https://github.com/user-attachments/assets/beb3122b-9aa4-4190-819b-b064b8492755)
I initially thought it might have been something I did wrong, but I started another project and the same thing happened.

### Reproduction

I honestly have no idea, only thing I did different from usual was importing a psd file from ibisPaint (which didn't work with another error about an 8BIM signature) so I had to import into CSP and save it again. I thought I should report it either way.

### System Architecture

x86_64

### Operating System

Windows

### Version

v0.8.5

**Comment by S-off-S** [comment]
Nevermind I just checked twice and this is a duplicate case (this what you get for not sleeping :))

**Comment by LunaTheFoxgirl** [comment]
This may have been fixed in the nightly builds, could you give that a shot?

**Comment by S-off-S** [comment]
I tried out the nightly build, but it didn't work for me. Instead of giving out the string error, the program crashed. I managed to make it work with the inpunpack tool though. Thanks so much!! :)
