### ISSUE TITLE
Hovering on options crashes

### ISSUE THREAD

**Issue by cheetosysst** [Inochi2D/inochi-creator#44]
### System
Version: [Beta 0.7.3 Prerelease 1 (w/ fixes)](https://github.com/Inochi2D/inochi-creator/releases/tag/v0.7.3-prerelease1) (Appimage)
OS: Linux 5.18.3-arch1-1

### Steps to reproduce
1. Open inochi creator, in the initial empty project, create a node under the puppet
2. Right click the node, hover on the delete option
3. When moving the cursor down to the last option, inochi creator crashes.

**Comment by cheetosysst** [comment]
[inochi-creator-crashdump.txt](https://github.com/Inochi2D/inochi-creator/files/8916089/inochi-creator-crashdump.txt)

**Comment by LunaTheFoxgirl** [comment]
Since this is already solved on main I will close it
