### ISSUE TITLE
No way to close dialogs when running under Wayland

### ISSUE THREAD

**Issue by grillo-delmal** [Inochi2D/inochi-creator#49]
When opening dialogs (like on `Edit > Settings` or `Help > About`), there is no way to close them when running inochi-creator under Wayland.

In the left image is how the dialog shows when drawn by the Wayland compositor, while on the right is when you run the application with `SDL_VIDEODRIVER=x11`, so it overrides to run under XWayland.

![image](https://user-images.githubusercontent.com/11585030/175651274-f249546b-aae7-42e5-a366-047c722609e1.png)

NOTE: The application currently won't even run under Wayland unless [support is added for bindbc-opengl](https://github.com/BindBC/bindbc-opengl/issues/29)

**Comment by LunaTheFoxgirl** [comment]
Fixed as of https://github.com/Inochi2D/inochi-creator/commit/43c9274a883a78bca5c384514cf6ec1a61833869
