### ISSUE TITLE
Depends on libraries without LICENSE file on their root dir

### ISSUE THREAD

**Issue by grillo-delmal** [Inochi2D/inochi-creator#51]
Just a reminder that the following libraries don't have a LICENSE file in their root directory.

bindbc-imgui
facetrack-d
gitver
i18n-d
psd-d

I preferred to open one ticket on this project instead than to go to each project to file a ticket since the maintainer is the same.

**Comment by LunaTheFoxgirl** [comment]
Thanks for letting me know, I'll add LICENSE files in a moment.

**Comment by LunaTheFoxgirl** [comment]
license files have been added to the repositories
