### ISSUE TITLE
Feature Request: Mirror a transformation/deformation

### ISSUE THREAD

**Issue by lualucky** [Inochi2D/inochi-creator#6]
I'd like to take the transformation/deformation on a part and copy it, and apply a mirrored version of it on a different parameter value. So for instance let's say I deform the head for turning to the left, I want to then copy and mirror that deformation for turning to the right.

**Comment by LunaTheFoxgirl** [comment]
@asahilina is working on this feature now

**Comment by LunaTheFoxgirl** [comment]
This feature has been implemented
