### ISSUE TITLE
Missing libSDL2 in AppImage

### ISSUE THREAD

**Issue by ljrk0** [Inochi2D/inochi-creator#66]
On a system without SDL2 (e.g., fedora Silverblue), run:

```
$ ./inochi-creator 
./inochi-creator: error while loading shared libraries: libSDL2-2.0.so.0: cannot open shared object file: No such file or directory
```

**Comment by LunaTheFoxgirl** [comment]
Known issue, we're still trying to find a way to compile SDL2 that has the least cross-distro conflicts. As such right now it relies on you having SDL2 and freetype installed on your base system

**Comment by ljrk0** [comment]
Ah, thank you, I didn't find the tracking issue if there is one.  If so, this should be closed obviously, otherwise I'd rename it to track this problem?

**Comment by orowith2os** [comment]
A small update, AppImages are being dropped for normal releases (being kept for prereleases, but I can work a flatpak out for that too, possibly), and a flatpak would be dropped into its place. Maybe that would be useful for you @ljrk0? It doesn't seem to have any dependency errors.

**Comment by ljrk0** [comment]
That's just as good (or even better IMHO).  It's not on Flathub yet, but as you mentioned it's WIP so I'm looking forward to it.  I can try helping package it, but I won't be in office til Oct.  If by then there's something left to do Flatpak wise I'm happy to assist.

**Comment by orowith2os** [comment]
Oh, I already have most of the work done, I'm just getting the automatic updating sorted out and then it'll be on the Beta branch. Glad to see you're interested lol. You can take a look at the progress on the package over here: https://github.com/flathub/flathub/pull/3502

**Comment by LunaTheFoxgirl** [comment]
We're moving to Flatpak, next version won't have an AppImage.
