### ISSUE TITLE
Logo on barebones build

### ISSUE THREAD

**Issue by grillo-delmal** [Inochi2D/inochi-creator#73]
Hi! I have a question regarding the logo

I wanted to add an icon to the barebones COPR build, but I don't want to add the Inochi2D logo because:
* Licensing problems (can't distribute assets on COPR that don't have free licenses n stuff [[0](https://docs.fedoraproject.org/en-US/legal/license-approval/)] [[1](https://docs.pagure.org/copr.copr/user_documentation.html#faq)])
* I want a different one so people don't confuse the barebones build with an official build.

For now I made this one, but since it's highly derivative (actually is the same one without color), I wanted to ask permission to distribute it (as CC-BY-SA or CC-BY-ND) and permission to add it to the repo.

![image](https://user-images.githubusercontent.com/11585030/188015468-7ea0b689-0223-490f-8d23-ed37c94d68aa.png)

If not, I can always use a non-derivative one, just wanted to check in here first before making the decision.

This question also applies to inochi-session, but I'll just ask here :)

**Comment by LunaTheFoxgirl** [comment]
I am not sure about this one specifically.
1. It has jagged edges which makes me suspect some weird scaling artefacts.
2. It may still imply that Inochi2D endorses the package which we don't for non-official-builds.

**Comment by grillo-delmal** [comment]
I thought so, I'll go with something different then, thanks for the answer 👍

**Comment by LunaTheFoxgirl** [comment]
If you do come up with something do lmk. I can set up so that it's included in the builds directly from the main repos

**Comment by grillo-delmal** [comment]
In the end I drew something and asked my couple to clean it up.

![logo](https://github.com/grillo-delmal/inochi-creator-rpm/blob/main/icon.png?raw=true "logo")

We licensed it as [CC-BY-SA](https://github.com/grillo-delmal/inochi-creator-rpm#about-the-icon), so you can include it if you like it 👍 

I'll close this ticket since this solves my problem
