### ISSUE TITLE
Permission for Flathub to distribute Inochi with branding enabled

### ISSUE THREAD

**Issue by orowith2os** [Inochi2D/inochi-creator#75]
Making this issue so I can reference it on the Flathub package so that they can be sure that it has permission to distribute the branding.

**Comment by LunaTheFoxgirl** [comment]
Permission is granted by the Inochi2D Project to redistribute full (Linux) flatpak builds with branding assets enabled on Flathub. These builds will eventually be maintained by us and as such are seen as official builds.
