### ISSUE TITLE
Arch AUR package request

### ISSUE THREAD

**Issue by Schala** [Inochi2D/inochi-creator#99]
### Validations

- [X] I have checked for similar feature requests and could not find any.
- [X] I have made sure this is not an already-existing feature.

### Description

I would like to make a packaging script for Inochi2D's suite. Unless officially taken from the AUR (Arch User Repository) and placed in Arch's official repo mirrors, the package is not prebuilt. Though automated, AUR packages must still require end users build the software from source itself.

### Suggested solution

AUR package scripts

**Comment by playmer** [comment]
The deps are a _little_ more involved than that, as I don't see bindbc-imgui setting USE_SUBMODULE_SOURCES in the dub.sdl yet (which is probably good for now). AppImage stuff won't be required for you, but you'll probably want to look at the bindbc linux requirements: https://github.com/Inochi2D/bindbc-imgui#dependencies-1

Mostly I think you'll just need to worry about things like `cmake`, `sdl2`, and `freetype`. But yeah whatever your equivilant of "a working C and C++ toolchain" is on arch, you'll need it. (Apologies, I did get Arch running at the time I wrote the docs, but I didn't think to record that bit down).

**Comment by grillo-delmal** [comment]
TBH I don't know anything about packaging in AUR or the related policies and intricacies about it, but I currently maintain the package in COPR for Fedora 36+ (which as I've heard, is kinda/sorta/like AUR for ArchLinux?) so I can give some pointers on my experience.

In this repository i have build scripts that build everything from source using podman (it still downloads non inochi related libraries from dub though)
https://github.com/grillo-delmal/inochi-creator-build

This is the main script in that repository that builds the software from scratch in the podman container, you can make it work in other environments if you tweak it and have leave the right things in the right places
https://github.com/grillo-delmal/inochi-creator-build/blob/main/scripts/build.sh

And here I have the packaging scripts for the COPR repo (TBH, I wouldn't recommend anyone to maintain something like this, hope to improve it in the future)
https://github.com/grillo-delmal/inochi-creator-rpm

Hope that this helps as ~~a cautionary story~~ reference ;)

**Comment by Schala** [comment]
Thanks everyone. I will take a look. As for the non-branding, can I use a desktop icon for the GUI executable?

**Comment by Schala** [comment]
Ah okay, so Inochi's own icon can't be used?

**Comment by grillo-delmal** [comment]
The icons are part of the [project branding](https://github.com/Inochi2D/branding), so [the rules](https://github.com/Inochi2D/inochi-creator#for-package-maintainers) on package distribution apply on them too.

In short, you can't use them.

**Comment by Schala** [comment]
> The icons are part of the [project branding](https://github.com/Inochi2D/branding), so [the rules on package distribution](https://github.com/Inochi2D/inochi-creator#for-package-maintainers) apply on them too.
> 
> There it says that you can ask for permission, but take into consideration that you would have to comply with the [project branding rules](https://github.com/Inochi2D/branding)
> 
> .... but honestly, this is something that Luna should answer, don't take my word on this.

Hmm... seems okay for making an automated packaging script for. I'm just concerned I might be culpable if someone then installs it from the AUR, then uses it to create NFTs

**Comment by LunaTheFoxgirl** [comment]
Oh you won't, you are not responsible for what people do with your package.

If someone does do that, I will personally tell the person in question who's making the NFT to eat shit.
